### PR TITLE
Style: Create and SignIn with Github button

### LINKED ISSUE #1594: [Fix]  Create and Sign in with Github button
### Details

The buttons on navbar (create, signin with github) are not appealing and styles are not relevant.

I want to improve it by adding modern styles and simple UI.

I really want to contribute to this wonderful project. Please assign this task to me under GSSoC '23. Thank You!

### Screenshots

image

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [x] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by rishuraj1**
## Fixes Issue

Closes #1594 

## Changes proposed

- Replaced the github png with classic github svg in Sign In button.
- added relevant styles for the Sign In button for light and dark mode in accordance with overall theme and color of app.
- added on hover effects to both create and Sign In buttons

- For mobile view, added the github svg instead of png
- added light color and dark color to it for light and dark mode respectively.

## Screenshots

image

image

image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
@rishuraj1 
It's not looking great in the light mode!
Also can you add a gradient to the create button as well as the plus symbol to the same color as the create text color.

Make sure it looks good in both dark and light mode!

**Comment by rishuraj1** [comment]
@Spyware007  alright! thanks for the feedback. I will update once its done.

**Comment by Spyware007** [comment]
@rishuraj1 Ping me once you are done with the changes!
I can see you had pushed something!

**Comment by rishuraj1** [comment]
@Spyware007  can you please check now. Thanks.

**Pull request merged**
