### PR TITLE
Donate Button added

### LINKED ISSUE #1039: [Add] New Donate Button
### Details

**Donate button**
It has an enter amount with sending it animation.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/111378171/eb1e11af-0523-497a-b309-d5918c345d62

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Killer2OP**
## Fixes Issue

Closes #1039 

## Changes proposed

Added  a donate button with amount animation

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Killer2OP** [comment]
@Spyware007 @TANYA-CHAN  please have look at my PR

**Comment by TANYA-CHAN** [comment]
> @Spyware007 @TANYA-CHAN please have look at my PR

Add your name in Data.js and reupload

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Killer2OP** [comment]
> > @Spyware007 @TANYA-CHAN please have look at my PR
> 
> Add your name in Data.js and reupload

Done

**Comment by Killer2OP** [comment]
> > > @Spyware007 @TANYA-CHAN please have look at my PR
> > 
> > 
> > Add your name in Data.js and reupload
> 
> Done
@Spyware007 @TANYA-CHAN please have look at my PR

**Review by TANYA-CHAN — APPROVED** [review]

**Pull request merged**
