### PR TITLE
docs: add workflow to update dependencies

### LINKED ISSUE #1044: [Add] Workflow for updating dependencies
### Details

Workflow to update dependencies: This workflow will handle updating dependencies as demonstrated in the image provided.

### Screenshots

image

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1044 

## Working

- `package-ecosystem`: Specifies that the package ecosystem is GitHub Actions. This indicates that Dependabot will manage the dependencies of the `GitHub Actions` workflows.

- `labels`: Assigns the label `📦 dependencies` to the pull request created for dependency updates. 

- `directory`: Sets the directory where the package.json file for GitHub Actions workflows is located. 

- `schedule`: Sets the schedule for running dependency updates. In this case, it is set to run weekly.

- `commit-message`: Sets the prefix for the commit messages generated for dependency updates. It will include `chore(deps)` as the prefix.

image

> In current state of the repository, this configuration is sufficient for the workflow.

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Spyware007
Could you please review this pull request :)

**Comment by TANYA-CHAN** [comment]
These kinds of PRs will be merged after tmrw please wait :)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
@Anmol-Baranwal We can add this once the new UI is published!

**Pull request closed without merging**
