### PR TITLE
Add to cart button is added

### LINKED ISSUE #876: Add to cart animated button
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Screenshot 2023-05-31 232413
Screenshot 2023-05-31 232418

This button is fully animated with the help of js.
Assign this issue to me under GSSOC'23

### PR DESCRIPTION
**Pull request by shraddha761**
## Fixes Issue

Closes #876 

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by shraddha761** [comment]
@Spyware007 please have a look

**Comment by shraddha761** [comment]
@TANYA-CHAN @Spyware007 please have a look

**Comment by TANYA-CHAN** [comment]
> @TANYA-CHAN @Spyware007 please have a look

Please describe what are you fixing or uploading. A preview is required

**Comment by shraddha761** [comment]
> > @TANYA-CHAN @Spyware007 please have a look
> 
> Please describe what are you fixing or uploading. A preview is requir is merge conflict 

> > @TANYA-CHAN @Spyware007 please have a look
> 
> Please describe what are you fixing or uploading. A preview is required

This branch has merge conflict and I solve that

**Comment by TANYA-CHAN** [comment]
> > > @TANYA-CHAN @Spyware007 please have a look
> > 
> > 
> > Please describe what are you fixing or uploading. A preview is requir is merge conflict
> 
> > > @TANYA-CHAN @Spyware007 please have a look
> > 
> > 
> > Please describe what are you fixing or uploading. A preview is required
> 
> This branch has merge conflict and I solve that

Have you added a button? If so then add it to the description template please. If not, then describe whatever you wish to fix over there please

**Comment by shraddha761** [comment]
> 

Yahhh this pr is for button

**Comment by Spyware007** [comment]
# Please check #1346

**Pull request merged**
