### PR TITLE
Added about-us page issue-1561

### LINKED ISSUE #1561: About Project page Redesign ❣️
The page contains information about the project, the project admin, some contributors who had made impactful contributions, and a timeline that I had already added.
Make sure to share the Figma file for your proposed design.

### PR DESCRIPTION
**Pull request by ManishaSwain8**
## Fixes Issue #1561
@Spyware007 
Closes #1561

## Changes proposed

Created about page (its not complete yet this PR is for preview)
I have added,
1.AboutUs (Folder)
     1.1. About.css
     1.2.About.jsx
      1.3.Contributor.jsx
      1.4 ContributorData.jsx
2.Timeline
 I have increased margin top only in the timeline.css file

## Checklist

- [ ] You've linked this PR to the correct issue.
- [ ] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by adity2911** [comment]
Can you upload some images to show the page.
Working video is highly appreciated.

**Comment by ManishaSwain8** [comment]
Yup 
Screenshot (97)
Screenshot (98)
Screenshot (99)
Screenshot (100)

@adity2911

**Comment by adity2911** [comment]
I think all is good. Can you change the Project Admin picture to the real one.
@Spyware007 @Akanksha-202 Your thoughts?

**Comment by Spyware007** [comment]
@ManishaSwain8 
Everything looks amazing!
Just a few fixes 
The margin/padding in the top of the about page in web version is too big.
We were using module.css, so you have to migrate from About.css to About.module.css!
You can refer to any other component folder!

**Comment by Spyware007** [comment]
@ManishaSwain8 Thank you so much for your contribution! 🚀
Please ⭐ the repo if you like it!
You can create PRs to add animation as you know an animation library. 🔥 
Looking forward to some more amazing contributions from you. 😀

**Comment by ManishaSwain8** [comment]
@Spyware007 I have created new issue for adding animation in about us page..I will start working once assigned:)

**Comment by Spyware007** [comment]
@ManishaSwain8 
Also check your discord dm!!

**Pull request merged**
