### PR TITLE
Added Paper Plane Button

### PR DESCRIPTION
**Pull request by varunshankar07**
This pull request introduces the implementation of the Paper Plane Button With Flying Animation, a fun and engaging interactive button for users. The purpose of this PR is to add this exciting button to the repository and make it available for users to enjoy.✈️
😊

Fixes: #683

### CODE REVIEW

**Comment by varunshankar07** [comment]
@Spyware007 Could You Check My PR And Merge It !!😊☺️

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by varunshankar07** [comment]
@PoorviShetty Could You Guide Me On How To Resolve The Conflicts On This Issue.. It Would be very helpful in solving my other 4 also☺️😊

**Comment by varunshankar07** [comment]
@Spyware007 could you help!!??

**Comment by Spyware007** [comment]
@varunshankar07 
You accidentally removed someone's name from the Data.is file.
Please check!

**Comment by varunshankar07** [comment]
@Spyware007 How to solve that?? it would if you show this one it would help me to solve the remaining 4 issues
Screenshot (107)

**Comment by varunshankar07** [comment]
@Spyware007 @PoorviShetty Could You Help ??

**Comment by varunshankar07** [comment]
@PoorviShetty It's nice of you that you resolved it ☺️ but it would be ever nice if you could teach me how you fixed it [ it was showing  something like master and main i could not understand it]

**Pull request merged**
