### PR TITLE
new animated button

### LINKED ISSUE #409: To add a new animated button to the list!
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

### PR DESCRIPTION
**Pull request by P766-spec**
## Fixes Issue

Closes #409 

## Changes proposed

Added the new Animatted button
## Screenshots
Screenshot (627)

Screenshot (628)

Screenshot (629)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by P766-spec** [comment]
Hey @PoorviShetty , the PR no is 953

**Comment by Jacinth-Mahanta** [comment]
Your branch is not in sync with the main project branch... It is lacking many buttons... Kindly sync and pull the main branch before send the PR otherwise someone else's buttons may be overwritten in case your commit is merged.

**Comment by P766-spec** [comment]
> Your branch is not in sync with the main project branch... It is lacking many buttons... Kindly sync and pull the main branch before send the PR otherwise someone else's buttons may be overwritten in case your commit is merged.

How can I do this I just created new PR because old one was not found

**Comment by P766-spec** [comment]
@PoorviShetty , done with template

**Comment by PoorviShetty** [comment]
Please resolve the merge conflicts

**Comment by P766-spec** [comment]
> Please resolve the merge conflicts

It's showing no acces something like that

**Comment by Souravvmishra** [comment]
Fix the conflicts or we have to close it

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Closing this as invalid!

**Pull request closed without merging**
