### PR TITLE
improved loading

### LINKED ISSUE #1867: Improving Loading and Working
## Currently
- The images on the website are taking time to load as they are in png/jpeg format.
- I will convert it into webp format
### Smaller File Size :
- WebP images typically have a smaller file size compared to PNG images while maintaining similar image quality. This results in faster webpage loading times, reduced bandwidth usage, and improved overall user experience.
### Wide Browser Support:
- WebP is supported by major web browsers, including Google Chrome, Opera, and Microsoft Edge. Additionally, popular image editing software like Adobe Photoshop and GIMP provide WebP support, making it easy to work with these files.
### Faster Image Loading:
- With smaller file sizes, WebP images can be downloaded faster by website visitors. This leads to quicker rendering of images on the page, resulting in a better user experience.
### Bandwidth Savings:
- The reduced file size of WebP images means less data needs to be transferred between the server and the user's device. This can be particularly advantageous for websites with a large number of images or for users on limited bandwidth connections.

### PR DESCRIPTION
**Pull request by parasss19**
## Fixes Issue

Closes #1867

## Changes proposed

- Go through each and every folder of the website
- Changed path of each and every media on the website to webp to improve loading and make website more efficient

### Original 
or

### Updated
up

## Checklist

- [ x] You've linked this PR to the correct issue.
- [x ] You have checked that the code is working correctly.
- [x ] You ⭐️ the repository!

### CODE REVIEW

**Comment by parasss19** [comment]
Hey @Souravvmishra Please review it

**Comment by Spyware007** [comment]
@parasss19 
Hello, do we need to change the icons which are used in meta tags to .webp too?

Is it necessary to do so?

**Comment by parasss19** [comment]
> @parasss19 Hello, do we need to change the icons which are used in meta tags to .webp too?
> 
> Is it necessary to do so?

In which files meta tags are present?

**Comment by parasss19** [comment]
> @parasss19 Hello, do we need to change the icons which are used in meta tags to .webp too?
> 
> Is it necessary to do so?

Hey i checked it i already changed the image into webp in meta tag too

**Pull request merged**
