### PR TITLE
Dark and light button

### PR DESCRIPTION
**Pull request by VardaPanchal005**
This is a dark mode and light mode button that changes theme with toggle.

Fixes issue: #431

  Checklist
 ✓ You've linked this PR to the correct issue.
 ✓ You have checked that the code is working correctly.
 ✓ You ⭐️ the repository!

### CODE REVIEW

**Comment by VardaPanchal005** [comment]
> > Please remove the unnecessary files outside public and src folders, and follow the naming convention for the files in the buttons folder
> 
> Can you check now

Actually  the files are used in the button so i cannot remove them @PoorviShetty

**Comment by VardaPanchal005** [comment]
Also I keep on resolving conflicts but as the time passes by the number of people following the steps of making pr keeps on creating conflicts in Data.js files I already updated the pr around 2-3 times

**Comment by TANYA-CHAN** [comment]
Upload files as per Readme please

**Comment by TANYA-CHAN** [comment]
> Upload files as per Readme please

@VardaPanchal005 Still can't merge because of extra files

**Comment by VardaPanchal005** [comment]
@TANYA-CHAN  can you check now

**Comment by TANYA-CHAN** [comment]
> @TANYA-CHAN can you check now

@Spyware007 please look into this as soon as possible

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Hello @VardaPanchal005 
Please spare us some time we are reviewing everything!
Will lyk if there's anything!
Thank you for your contribution 🎉

**Comment by TANYA-CHAN** [comment]
> Hello @VardaPanchal005 Please spare us some time we are reviewing everything! Will lyk if there's anything! Thank you for your contribution 🎉

@

**Comment by Souravvmishra** [comment]
Fix Conflicts

**Comment by VardaPanchal005** [comment]
> Fix Conflicts

Can you check now

**Pull request merged**
