### PR TITLE
Created and added animating button

### LINKED ISSUE #1264: [Add] Adding a new animated button
### Details

Hello @Spyware007 
I would like to propose my animated button design to your project. A simple yet minimalistic design where the flash of white covers the button when we hover to the button. 

### Screenshots
Screenshot (224)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Manudasari265**
## Fixes Issue

Closes #1264 

## Changes proposed
Added and modified my animating button 

## Screenshots
Screenshot (224)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Manudasari265** [comment]
@Spyware007 Kindly check and merge my pull request

**Comment by TANYA-CHAN** [comment]
You should add your Data.js file also

**Comment by Manudasari265** [comment]
> You should add your Data.js file also

but I have created this button using only HTML and CSS. is data.js file  internal file of the project or is it mine?

**Comment by TANYA-CHAN** [comment]
> > You should add your Data.js file also
> 
> Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.

Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe

**Comment by Manudasari265** [comment]
> > > You should add your Data.js file also
> > 
> > 
> > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> 
> Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe

@TANYA-CHAN I have added my username in data.js file. please review it and merge my request.

**Comment by TANYA-CHAN** [comment]
Please remove package.lock file also 

> > > > You should add your Data.js file also
> > > 
> > > 
> > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > 
> > 
> > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> 
> @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Manudasari265** [comment]
> Please remove package-lock file also
> 
> > > > > You should add your Data.js file also
> > > > 
> > > > 
> > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > 
> > > 
> > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > 
> > 
> > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.

deployment is getting failed after I removed package-lock.json file.

**Comment by TANYA-CHAN** [comment]
> > Please remove package-lock file also
> > > > > > You should add your Data.js file also
> > > > > 
> > > > > 
> > > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > > 
> > > > 
> > > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > > 
> > > 
> > > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.
> 
> deployment is getting failed after I removed package-lock.json file.

hasn't been removed

**Comment by Manudasari265** [comment]
> > > Please remove package-lock file also
> > > > > > > You should add your Data.js file also
> > > > > > 
> > > > > > 
> > > > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > > > 
> > > > > 
> > > > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > > > 
> > > > 
> > > > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.
> > 
> > 
> > deployment is getting failed after I removed package-lock.json file.
> 
> hasn't been removed

there are two files naming package-lock.json and package.json and i removed lock.json file should I have to remove both the files?

**Comment by TANYA-CHAN** [comment]
> > > > Please remove package-lock file also
> > > > > > > > You should add your Data.js file also
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > > > > 
> > > > > > 
> > > > > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > > > > 
> > > > > 
> > > > > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.
> > > 
> > > 
> > > deployment is getting failed after I removed package-lock.json file.
> > 
> > 
> > hasn't been removed
> 
> there are two files naming package-lock.json and package.json and i removed lock.json file should I have to remove both the files?

I can only see the lock file here so just remove that and reupload

**Comment by Manudasari265** [comment]
> > > > > Please remove package-lock file also
> > > > > > > > > You should add your Data.js file also
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > > > > > 
> > > > > > > 
> > > > > > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > > > > > 
> > > > > > 
> > > > > > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.
> > > > 
> > > > 
> > > > deployment is getting failed after I removed package-lock.json file.
> > > 
> > > 
> > > hasn't been removed
> > 
> > 
> > there are two files naming package-lock.json and package.json and i removed lock.json file should I have to remove both the files?
> 
> I can only see the lock file here so just remove that and reupload

i removed both the files can you pls check once but deployment is getting failed

**Comment by TANYA-CHAN** [comment]
> > > > > > Please remove package-lock file also
> > > > > > > > > > You should add your Data.js file also
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Sorry I just missed the third step of adding my code to src/data.js folder. can you guide me on how to add it while i have already created a pull request now.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Please copy and paste Data.js from the original directory and add your name at the very end of the file, recheck and upload only this file here again. If required please look into ReadMe
> > > > > > > 
> > > > > > > 
> > > > > > > @TANYA-CHAN I have added my username in data.js file. please review it and merge my request.
> > > > > 
> > > > > 
> > > > > deployment is getting failed after I removed package-lock.json file.
> > > > 
> > > > 
> > > > hasn't been removed
> > > 
> > > 
> > > there are two files naming package-lock.json and package.json and i removed lock.json file should I have to remove both the files?
> > 
> > 
> > I can only see the lock file here so just remove that and reupload
> 
> i removed both the files can you pls check once but deployment is getting failed

package lock is still there, you can create a new PR then

**Pull request closed without merging**
