### PR TITLE
Fixed the Problem of mouse hover over the "Created by <user>" Box.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
Issue #523 

Solved the Issue which was bad cursor pointer when pointed onto the "Created by username". 
As you can see below in the video, I have shown both the old cursor and new cursor:

| *Mouse Cursor over the Top Box - Old* |

https://github.com/Spyware007/Animating-Buttons/assets/100849696/0605f716-63c4-468d-b21f-1f3eaba9af87

| *Mouse Cursor over the Top Box - New* |

https://github.com/Spyware007/Animating-Buttons/assets/100849696/ec41f325-3884-4987-a06e-477b011949ab

Please Review this PR and Kindly Merge it!

Contributor - Sabhi Sharma (GSSOC'23)

### CODE REVIEW

**Comment by sabhisharma-ise** [comment]
Hey @PoorviShetty could you've added a level3 to it please!

**Comment by sabhisharma-ise** [comment]
@Spyware007 Hey, It passed all checks and has no conflicts. Can you review and merge it!

**Comment by Spyware007** [comment]
@sabhisharma-ise Please resolve the conflicts!

**Comment by sabhisharma-ise** [comment]
@Spyware007 Hey, please review the PR 
I've resolved the merge conflicts now!

**Comment by Spyware007** [comment]
@sabhisharma-ise  I'm extremely sorry!
But I guess due to the latest merges there are still some conflicts.

**Comment by sabhisharma-ise** [comment]
@Spyware007 
Check now

**Comment by Spyware007** [comment]
@sabhisharma-ise 



Failed to compile.
--
12:26:10.863 |  
12:26:10.863 | Module not found: Error: Can't resolve '../../Functions/Download' in '/vercel/path0/src/components/Main'
12:26:10.863 |  
12:26:10.863 |  
12:26:10.886 | error Command failed with exit code 1.
12:26:10.886 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:26:10.902 | Error: Command "yarn run build" exited with 1
12:26:11.180 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1

Here's the vercel error.
It's saying module not found.
Means you accidentally imported something that is not defined.

**Comment by sabhisharma-ise** [comment]
It wasn't coming yesterday, but I'm not sure why it came now.

**Pull request closed without merging**
