### PR TITLE
new click me button added under the folder shreyal0007 in public>buttons

### PR DESCRIPTION
**Pull request by shreyal0007**

### CODE REVIEW

**Comment by Spyware007** [comment]
@shreyal0007 Please remove the package-lock.json fie from the commits. 
Also, you forgot the Data.js part!

**Comment by shreyal0007** [comment]
Could you please tell me what I have to remove from that file .

**Comment by Spyware007** [comment]
@shreyal0007 go to the last commit in your code editor
then remove the package-lock.json from the commits 
push the code

**Comment by shreyal0007** [comment]
Ok I'll do it give me some time

**Comment by shreyal0007** [comment]
i am not able to push the code. it is saying access denied.

**Comment by Spyware007** [comment]
@shreyal0007 Make sure you are pushing in your fork repository!

**Comment by PoorviShetty** [comment]
Please resolve your merge conflicts!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this?

**Pull request closed without merging**
