### PR TITLE
Sabhi branch

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
Issue #297 ✅

Added a New Button in the Repo, Please have a look and merge the PR

The button looks like the following:

image

### CODE REVIEW

**Comment by sabhisharma-ise** [comment]
@Spyware007 Hey, Please Review my PR

**Comment by Spyware007** [comment]
https://github.com/Spyware007/Animating-Buttons/assets/89961974/1c8f5daa-aaba-4239-812f-45f6c0425a08
@sabhisharma-ise 

Your button is not centered aligned.
Kindly fix it and it will get merged.

**Comment by sabhisharma-ise** [comment]
@Spyware007 I have centered the button as you can see below:

image

Now, you can successfully merge my PR

**Comment by Spyware007** [comment]
Cool @sabhisharma-ise .
Amazing work! 🤩 

Looking forward to more contributions from you! 🧑‍💻
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
