### PR TITLE
Cart button using JavaScript  [ GSSOC'23 ]

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## Fixes Issue

#898 

## Changes proposed

Adding cart button using JavaScript!

## Video

https://github.com/Spyware007/Animating-Buttons/assets/114821855/06ec0e49-690a-474c-ac95-1fcb3d7824c2

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
when I try to fix the failed issues in Deployment it's showing like as earlier

Page Not Found – Vercel - Google Chrome 05-06-2023 11_27_57

**Comment by Kalivarapubindusree** [comment]
Yes completed Please check! @PoorviShetty

**Comment by Kalivarapubindusree** [comment]
Can you please review my pr again?? 
Is there any change to be done yet ?? @PoorviShetty

**Comment by Kalivarapubindusree** [comment]
can you please review cart button pr #985 
I have done all the process as you said can you please merge my pr? @PoorviShetty @Spyware007

**Review by TANYA-CHAN — APPROVED** [review]

**Review by TANYA-CHAN — APPROVED** [review]

**Pull request merged**
