### PR TITLE
New Animated Buttons Added

### PR DESCRIPTION
**Pull request by Nishusk**
---

# Animated Buttons Collection

The Animated Buttons Collection is a set of interactive button components designed to enhance user experiences and add visual appeal to web interfaces. Each button within the collection offers unique animations and design elements to elevate your website or application.

## Key Features

- Interactive Animations: Engage users with fluid and captivating animations triggered by user interactions, such as hovering or clicking the buttons.
- Customizable Aesthetics: Tailor the appearance of each button to match your project's branding or theme using customizable options such as colors, sizes, and other visual properties.
- Easy Integration: The buttons are designed for easy integration into your project. Follow the provided documentation and integration steps to effortlessly incorporate them into your user interface.

## Available Buttons

1. Truck Button
   - Description: The Truck Button simulates the movement of a truck and adds an element of elegance and interactivity to your website or application.
   - Key Features: 
     - Interactive Animation: Engage users with a seamless animation sequence triggered by clicking the button.
     - Dual States: Seamlessly transitions between default and success states, providing intuitive visual feedback.
     - Customizable Design: Easily adjust colors, sizes, and other visual properties using CSS variables.
     - Easy Integration: Powered by the GSAP library, requiring simple initialization with a few lines of JavaScript code.

2. Neumorphic Button
   - Description: The Neumorphic Button features a neumorphic design, offering a tactile and three-dimensional appearance.
   - Key Features:
     - Neumorphic Design: Stylish button design with a modern, tactile feel.
     - Hover Animations: Smooth transitions with subtle scale and opacity effects when users hover over the button.
     - Cross-Browser Compatibility: Tested and optimized for compatibility across modern web browsers.

3. Glass Button
   - Description: The Glass Button incorporates a sleek and transparent design, creating a modern and sophisticated look.
   - Key Features:
     - Transparent Appearance: Stylish and minimalistic button design with a glass-like effect.
     - Customizable: Adjust colors, sizes, and other visual properties to match your project's aesthetics.
     - Interactive Hover Effects: Smooth and subtle animations on hover, enhancing user interaction and engagement.

4. Go Button
   - Description: The Go Button is a simple and versatile button designed to provide a clear call-to-action in your user interface.
   - Key Features:
     - Minimalistic Design: Clean and straightforward button design, ideal for emphasizing important actions.
     - Customizable: Easily adjust colors, sizes, and other visual properties to fit your project's branding.
     - Easy Integration: Simple implementation with HTML and CSS code, making it easy to integrate into your projects.

5. CSS Animated Hover Effect Buttons
   - Description: These buttons utilize CSS animations to create eye-catching hover effects, adding a dynamic touch to your user interface.
   - Key Features:
     - Variety of Effects: Choose from a collection of pre-designed CSS animations to create visually appealing hover effects.
     - Easy Customization: Adjust colors, timings, and other animation properties to customize the buttons to your liking.
     - Cross-Browser Compatibility: Tested and optimized for compatibility across modern web browsers.

## Usage

The Animated Buttons Collection is versatile and can be used in a variety of applications, including e-commerce websites, blogs, portfolios, or any project that aims to enhance user engagement and interactivity.

To integrate the buttons into your project:
1. Follow the comprehensive documentation and integration steps provided for each button.
2. Copy the HTML and CSS code for the desired button(s).
3. Paste the

 code into your web page.
4. Customize the buttons' appearance to align with your project's aesthetics.

Feel free to modify and adapt the code to suit your specific needs. The buttons' code is well-structured and easy to understand, enabling further customization and integration into existing projects.

## Contributions

Contributions to the Animated Buttons Collection are welcome! If you have ideas for additional button designs or animation enhancements, you can submit a pull request following the guidelines outlined in the project's contributing documentation.

## License

The Animated Buttons Collection is released under the permissive MIT License, granting you the freedom to use, modify, and distribute the buttons without restrictions.

## Support

If you encounter any issues or have questions regarding the Animated Buttons Collection, please open an issue on the project's GitHub repository. The project maintainers and the community will be happy to assist you.

---

### CODE REVIEW

**Comment by Nishusk** [comment]
Please checkout my newly Added buttons  @Spyware007

**Comment by Nishusk** [comment]
> Please checkout my newly Added buttons @Spyware007

I tried finding the conflicts in package-lock.json files but didn't find any.

**Comment by Nishusk** [comment]
Subject: Help Needed: Resolving Merge Conflicts in Animating-Buttons

Dear Community/Team/Developer,

I hope this message finds you well. I am writing to seek assistance with
resolving merge conflicts in the Animating-Buttons open-source project. I
am facing challenges in resolving the conflicts and would greatly
appreciate any guidance or support you can provide.

Description:
I am currently working on a feature branch called "conflict-resolution,"
which is based on the latest development branch of the project. While
attempting to merge my changes into the main branch, I encountered several
conflicts that I am having difficulty resolving.

I have followed the standard Git conflict resolution process, running
commands such as `git status` and `git diff` to identify the conflicting
files. However, upon reviewing the files, I find it challenging to
determine the conflicting sections and resolve them effectively.

I have also reviewed the project documentation and searched online
resources for guidance, but I haven't been able to find a solution specific
to the conflicts I'm experiencing.

I kindly request your expertise in helping me understand the conflicts more
clearly and guiding me on the appropriate steps to resolve them. It would
be immensely valuable if you could provide insights, techniques, or
specific commands that can assist in identifying and resolving the
conflicts in a smooth and efficient manner.

Additional Information:
- Operating System: Windows
- Git Version: 2.40.1.windows.1
- Development Environment: Visual Studio Code Editor
- Repository Link: [
https://github.com/Nishusk/Animating-Buttons](https://github.com/Nishusk/Animating-Buttons)

I am eager to learn and contribute to the Animating-Buttons project, and
resolving these conflicts will enable me to move forward with my work. Your
assistance will not only help me personally but also benefit the entire
project and its community.

Thank you very much for your time and consideration. I genuinely appreciate
your support in helping me overcome these merge conflicts. Please let me
know if there are any further details or clarifications you require.

Looking forward to your guidance and suggestions.

Best regards,

Nishu Kumari GSSoC '23
GitHub: [Nishusk](https://github.com/Nishusk)

**Comment by Souravvmishra** [comment]
@Nishusk Are you working on this?

**Comment by Nishusk** [comment]
> @Nishusk Are you working on this?
No Sir but i'm trying to solve the conflicts.

**Pull request closed without merging**
