### PR TITLE
New Button Added

### PR DESCRIPTION
**Pull request by rayarka26**
With a jumping effect for the Button for GirlScript summer of Code 2023

### CODE REVIEW

**Comment by Spyware007** [comment]
Please add your GitHub username in Data.js
Also, Pull first to see the latest changes.

**Comment by rayarka26** [comment]
sir all the problems solved please merge //gssoc23

**Comment by rayarka26** [comment]
Mine button is 2nd one

**Comment by Arkapravaray** [comment]
@Spyware007 please check

**Comment by rayarka26** [comment]
@Spyware007 please check

**Comment by Spyware007** [comment]
@rayarka26 Change styles.css to style.css 
And it will be merged then!

**Comment by rayarka26** [comment]
@Spyware007 please check

**Comment by Spyware007** [comment]
@rayarka26  Really Amazing!
Thank you so much for your contribution.🌟
Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️ 
https://www.linkedin.com/in/om-gawande/

**Pull request merged**
