### PR TITLE
Navbar components aligned.

### PR DESCRIPTION
**Pull request by ydvmudit07**
# _Description_
The components in the navbar were not aligned. After some minor changes in the navbar.css file, it's now fixed! Kindly review and merge the same.

## _Issue_
#920  

## _Changes_
The navbar earlier looked as follows:

Screenshot 2023-06-03 163438

After changes the navbar looks as follows:

image

### CODE REVIEW

**Comment by ydvmudit07** [comment]
Issue #920 resolved!
Kindly review and merge. :)

**Comment by ydvmudit07** [comment]
@Spyware007 , kindly review the changes and merge. :)

**Comment by TANYA-CHAN** [comment]
Please hold, these kinds of issues will be merged after tmrw

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by ydvmudit07** [comment]
> Please hold, these kinds of issues will be merged after tmrw

@TANYA-CHAN , I guess this issue is still not merged, kindly look into it. :)

**Pull request merged**
