### PR TITLE
3D CSS Hover Effect Button Component

### LINKED ISSUE #1194: [Add] 3D CSS Hover Effect Button Component
### Details

I propose the addition of a new button component to our project that features a 3D CSS hover effect. This component will enhance the visual appeal of the buttons and provide an engaging user experience. 

Key Features:
- 3D Appearance: The button will have a visually appealing 3D design, giving it depth and making it stand out on the page.
- Hover Effect: When the user hovers over the button, a subtle shadow effect will be applied, providing visual feedback and enhancing the interactive nature of the buttons.

By adding this 3D CSS hover effect button component, we aim to improve the visual aesthetics of our project, create a more engaging user experience, and provide a flexible and customizable solution for button styling.

### Screenshots

Screenshot (833)
Screenshot (834)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishusk**
## Fixes Issue

Closes #1194

## Changes proposed
The 3DHoverButton component is a button component that features a 3D CSS hover effect, adding depth and interactivity to enhance the visual appeal and user experience of buttons.

### Key Features

1. 3D Appearance: The button has a visually appealing 3D design, giving it depth and making it stand out on the page.
2. Hover Effect: When the user hovers over the button, a subtle shadow effect is applied, providing visual feedback and enhancing the interactive nature of the buttons.
3. Dev Mode: The component includes a "Dev Mode" feature, allowing developers to switch between different button styles for testing and debugging purposes.

### CSS Classes

The 3DHoverButton component uses the following CSS classes:

- `3d-hover-button`: Applied to the button element to style it as a 3D button with a hover effect.
- `container`: Applied to a container element to provide a layout for the button and the "Dev Mode" switch.
- `switch`: Applied to a container element for the "Dev Mode" switch.
- `switch input`: Applied to the input element of the "Dev Mode" switch.

### Browser Compatibility

The 3DHoverButton component is compatible with modern web browsers, including Chrome, Firefox, Safari, and Edge. Please note that Internet Explorer may have limited or no support for some of the CSS features used in the component.
## Screenshots
Screenshot (833)
Screenshot (834)
Screenshot (838)
Screenshot (839)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers
Thank you for taking the time to review the proposed changes and additions to the project. We appreciate your feedback and suggestions. Here are some specific areas where we would appreciate your attention:

1. CSS Optimization: Please review the CSS code to ensure it follows best practices and is optimized for performance. If there are any opportunities for improvement or simplification, please provide your suggestions.

2. Cross-Browser Compatibility: Please test the 3DHoverButton component on different browsers and devices to ensure compatibility and address any issues that may arise. If there are any known limitations or browser-specific workarounds, please document them in the compatibility section.

3. Accessibility Considerations: Accessibility is an important aspect of any UI component. Please verify that the 3DHoverButton component is accessible and adheres to WCAG (Web Content Accessibility Guidelines) standards. If there are any accessibility improvements that can be made, please let us know.

4. Code Structure and Organization: Review the code structure and organization to ensure it is clear, maintainable, and follows established coding conventions. If there are any areas that can be improved or refactored for better readability or maintainability, please provide your recommendations.

5. Documentation Clarity: Please assess the clarity and comprehensiveness of the provided documentation. If there are any areas that need further explanation or additional examples, please let us know so we can make the necessary updates.

We value your expertise and input in making these enhancements to the project. Thank you for your thorough review and assistance in improving the quality of our codebase.
Screenshot (838)
Screenshot (839)

### CODE REVIEW

**Comment by Souravvmishra** [comment]
@Nishusk Can You Fix The Conflicts?

**Comment by Souravvmishra** [comment]
Take Your Time @Nishusk

**Comment by TANYA-CHAN** [comment]
Please upload each button file separately, there should be only 3-4 files in the PRs not 39, recheck

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by TANYA-CHAN** [comment]
Please add a Data.js file

**Pull request merged**
