### PR TITLE
Added button

### PR DESCRIPTION
**Pull request by aniketburman014**
Add animated buttons using HTML and CSS. 🚀 #141

### CODE REVIEW

**Comment by aniketburman014** [comment]
@Spyware007  I have made PR, please review it .

**Comment by Spyware007** [comment]
Hello @aniketburman014 
Please uncommit the package-lock.json
It will be merged then!

**Comment by aniketburman014** [comment]
I have uncommitted the package-lock.json. please check and merge it.

**Comment by PoorviShetty** [comment]
@aniketburman014 There seems to be a merge conflict, please fix it

**Comment by aniketburman014** [comment]
Sorry for the inconvenience. As I am new to GitHub, please check whether the issue has been resolved or not.

**Comment by Spyware007** [comment]
@aniketburman014 



Failed to compile.
--
02:14:17.307 |  
02:14:17.307 | [eslint]
02:14:17.307 | src/Data.js
02:14:17.308 | Syntax error: Unexpected token, expected "," (179:2) (179:2)
02:14:17.308 |  
02:14:17.308 |  
02:14:17.341 | Error: Command "npm run build" exited with 1
02:14:17.528 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

This is the issue.

You are missing a semicolon in the Data.js file!

**Pull request merged**
