### PR TITLE
[GSSoC 2023] Animation Button using HTML and CSS

### PR DESCRIPTION
**Pull request by Anik-Banerjee364**
part of GSSoC 2023 program

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by Anik-Banerjee364** [comment]
resolved

**Comment by Anik-Banerjee364** [comment]
> Hi, there seems to be a merge conflict, please resolve it

May you please look into it now

**Comment by Anik-Banerjee364** [comment]
look into it once,

**Pull request merged**
