### PR TITLE
Added animation to About us issue-1616                         

### LINKED ISSUE #1616: [Animation] Adding animation to the About page
### Details

Animation to About page using Framer Motion.
Do assign under Gssoc 2023 : |)

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by ManishaSwain8**
## Fixes Issue

Closes #1616 

## Changes proposed

1.wave animation
2.opacity animation
3.use of Stagged children
4.fade in /out
5.onscroll animation 

## Checklist

- [x ] You've linked this PR to the correct issue.
- [ x] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
Screenshot 2023-06-30 at 3 03 10 AM

Syntax error in Timeline.module.css @ManishaSwain8

**Comment by ManishaSwain8** [comment]
Give me some min

**Comment by ManishaSwain8** [comment]
@Spyware007 you can check it now

**Comment by Spyware007** [comment]
https://github.com/Spyware007/Animating-Buttons/assets/89961974/e262c20f-ce0f-4508-a4d7-a0a287f4a807

It's jumping?
Is it supposed to be like this?
Can you make it fade in or slide up?

**Comment by ManishaSwain8** [comment]
@Spyware007 
I had added the bounce effect as I thought that particular section should be highlighted..
I will change if not req.

**Comment by ManishaSwain8** [comment]
@Spyware007 I have added new animation check it out !

**Comment by Spyware007** [comment]
@ManishaSwain8 In the mobile view can you make the size of images and text of contributors somewhat smaller.
It's too big!

**Comment by ManishaSwain8** [comment]
Ok I will push the updated code

**Comment by ManishaSwain8** [comment]
@Spyware007 check out.. if this works

**Comment by Spyware007** [comment]
@ManishaSwain8 Thank you so much!

**Pull request merged**
