### PR TITLE
Share btn

### PR DESCRIPTION
**Pull request by PriyankaTamhankar01**

### CODE REVIEW

**Comment by Spyware007** [comment]
@PoorviShetty Look into this I think that if we merged this It will remove all the others newly added button!

**Comment by PoorviShetty** [comment]
@PriyankaTamhankar01 Please don't entire modify Data.js

**Comment by PoorviShetty** [comment]
Hi, are you still working on this?

**Comment by PoorviShetty** [comment]
Closing due to lack of activity

**Pull request closed without merging**
