### PR TITLE
Added 3D Button with shadow Effect

### LINKED ISSUE #1166: [Add]3D Button with Hover Shadow Effect
### Details

I would like to propose the addition of a 3D button component to the open source project. The button should have a 3D appearance with a subtle shadow effect that disappears on hover.

Features:
1. 3D Appearance: The button should have a visually appealing 3D design, giving it depth and making it stand out on the page.
2. Hover Shadow Effect: When the user hovers over the button, the shadow should fade out smoothly, providing visual feedback to the user.
Expected Outcome:

By adding this 3D button component with a hover shadow effect, we can enhance the visual appeal of the project and provide a more engaging user experience.

### Screenshots

Screenshot (830)
Screenshot (831)
Screenshot (832)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishusk**
## Fixes Issue

Closes #1166

## Changes proposed
The 3D button component is a visually appealing button with a 3D design and a hover shadow effect. It enhances the user interface by providing a distinctive appearance and interactive feedback.

## Hover Shadow Effect
The 3D button component includes a hover shadow effect by default. When the user hovers over the button, the shadow fades out smoothly, providing visual feedback. This effect is implemented using the JavaScript code in the `3d-button.js` file. If you want to customize the hover shadow effect, you can modify the JavaScript code accordingly.

## Compatibility
The 3D button component is designed to work in modern web browsers. It is compatible with the latest versions of Chrome, Firefox, Safari, and Edge. Please note that Internet Explorer does not fully support some of the CSS properties and JavaScript features used in the component.

## Screenshots

Screenshot (830)
Screenshot (831)
Screenshot (832)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers
Certainly! Here's an additional section you can include in your documentation specifically for reviewers:

## Note for Reviewers
Thank you for reviewing the proposed addition of the 3D button component to  project. We value your feedback and input in ensuring the quality and usability of our project.
Please pay attention to the following aspects during the review process:

1. **Code Quality**: Review the code implementation of the 3D button component, ensuring it follows best practices, is modular, and maintainable.
2. **Compatibility and Accessibility**: Verify that the component is compatible with modern web browsers and adheres to accessibility standards.
3. **Performance**: Assess the performance impact of the component, considering factors such as file size, rendering speed, and overall user experience.
4. **Customization Options**: Evaluate the flexibility of the component in terms of customization and integration with existing project styles.
5. **Documentation**: Review the clarity, completeness, and accuracy of the documentation provided for the 3D button component.
6. **Testing**: Test the component in different scenarios to ensure its functionality, responsiveness, and compatibility.

Your feedback and suggestions are highly appreciated and will contribute to the overall improvement of our open source project. Please provide your comments, concerns, and recommendations through the appropriate review channels.

Thank you for your valuable time!

### CODE REVIEW

**Comment by TANYA-CHAN** [comment]
Too many files, only reupload follwing ReadMe

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
resolve conflicts

**Comment by Nishusk** [comment]
> resolve conflicts

Sure sir

**Review by adity2911 — APPROVED** [review]

**Pull request merged**
