### PR TITLE
added  animated loading button

### PR DESCRIPTION
**Pull request by silky-modi22**
## Fixes Issue

Closes #1216 

## Changes proposed

I add animated loading button

## Screenshots

image

please merge my PR under GSSOC 2023

### CODE REVIEW

**Comment by Souravvmishra** [comment]
You Forget To Add Your Name In Data.js

**Comment by silky-modi22** [comment]
Sorry, I will add my name

**Comment by silky-modi22** [comment]
Please check I added my name in Data.js

**Comment by Souravvmishra** [comment]
Fix The Conflicts

**Comment by silky-modi22** [comment]
Please check i think conflict is fix now

**Pull request merged**
