### PR TITLE
Buttons dark theme

### PR DESCRIPTION
**Pull request by rbeaujon**
The buttons were adapted for dark mode

### CODE REVIEW

**Comment by Spyware007** [comment]
I think this is not the correct way to adaption to dark mode.
When the user downloads the code for any button, they will also get this dark mode script tag which is unnecessary for them.
The solution to this issue is to add a background color for the body tag in each button's style.css files.

@rbeaujon

**Comment by rbeaujon** [comment]
I was thinking change the style.css for work with the same BG in both
mode.... but I was thinning this way was better but I see I was wrong. I'll
change them just now

**Comment by rbeaujon** [comment]
I pushed the changes, please let me know about this approach. Thank you

**Comment by Arjun-Ingole** [comment]
@Spyware007 Seems fine in my opinion, Changing the color to something that visible in both dark mode and light mode is a good work around in dealing with this issue, Great work by the way @rbeaujon

**Review by Arjun-Ingole — APPROVED** [review]

**Pull request merged**
