### PR TITLE
contribute under GSSOC'23 #267

### PR DESCRIPTION
**Pull request by Pritam991**

### CODE REVIEW

**Comment by Spyware007** [comment]
@Pritam991 Change the name of your CSS file to style.css and link it to the HTML file.

**Comment by Pritam991** [comment]
@Spyware007 done ✅

**Comment by Spyware007** [comment]
Please update the branch before pushing any further commits. 🚀

**Comment by PoorviShetty** [comment]
@Pritam991 Hi, there are some merge conflicts, can you look into it?

**Comment by Spyware007** [comment]
@Pritam991  Finally its done, I fixed the issues with commas
Looking forward to more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
