### PR TITLE
delete button added

### LINKED ISSUE #1406: [Add] Delete Button
### Details

_This button has cool animation for delete somthing_

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by khushbumaheshwarii**
## Fixes Issue

Closes #1406 

## Checklist

- [ ] You've linked this PR to the correct issue.
- [ ] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
Good Work

**Comment by adity2911** [comment]
Kindly provide a screeenshot or video recording of the button on your other PRs.

**Comment by khushbumaheshwarii** [comment]
> Kindly provide a screeenshot or video recording of the button on your other PRs.

Kindly check my other PRs , i just added screenshot of the button on them.

**Pull request merged**
