### PR TITLE
Added a button #406

### PR DESCRIPTION
**Pull request by Krishi1211**
Checkout My new button!!

### CODE REVIEW

**Comment by Krishi1211** [comment]
@Spyware007 @PoorviShetty please look at my new button xD 
And please merge it into the main :)

**Comment by Spyware007** [comment]
@Krishi1211 you haven't linked the css file to the HTML file.

also use the entire code of HTML and don't just write the part inside of the body tag.

It will get merged then!
 All the best!

**Comment by Krishi1211** [comment]
@Spyware007 Check it out!!

**Comment by Spyware007** [comment]
@Krishi1211 Well done! 🤩

Looking forward for more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
