### PR TITLE
Rishabh3243 button

### PR DESCRIPTION
**Pull request by Rishabh3243**
Created a style button

### CODE REVIEW

**Comment by VishalVinayRam** [comment]
can u assign this to me

**Comment by PoorviShetty** [comment]
Hi, please check the names of the files, do refer README.md

**Comment by Spyware007** [comment]
@Rishabh3243 Are you still working on this?

You just have to rename the html files to index.html
And CSS files to style.css

Also, change the name of CSS file in link tag.

**Comment by Spyware007** [comment]
@VishalVinayRam This is a PR.
Please create a issue!

**Comment by VishalVinayRam** [comment]
Yes

**Pull request closed without merging**
