### PR TITLE
Added a new button

### PR DESCRIPTION
**Pull request by marshadkhn**
Done with #452 
Branch name - marshadkhn

Screenshots
Screenshot 2023-05-24 181645
Screenshot 2023-05-24 181720

Review and merge my code
**Thank you**

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by marshadkhn** [comment]
Ok I will send a new PR for sure

**Comment by marshadkhn** [comment]
Hey @PoorviShetty I resolved the conflict
Merge the PR

**Comment by Spyware007** [comment]
@marshadkhn Great work

Looking forward to more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
