### PR TITLE
Styling added to the scrollbar

### PR DESCRIPTION
**Pull request by HimanshuNarware**
Closes #issue_number
#1628
## Changes proposed
Added styling to the scrollbar of the website.
## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/83147410/3fa70ebf-5e99-4c8f-8a70-05b487326563

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Souravvmishra** [comment]
I can't see any difference in the scroll bar on my mobile device. Please Check

**Comment by HimanshuNarware** [comment]
> I can't see any difference in the scroll bar on my mobile device. Please Check

ok

**Comment by HimanshuNarware** [comment]
> I can't see any difference in the scroll bar on my mobile device. Please Check

@Souravvmishra  I think is because of the small screen

**Comment by Souravvmishra** [comment]
> > I can't see any difference in the scroll bar on my mobile device. Please Check
> 
> @Souravvmishra  I think is because of the small screen
> 
> 
> 
> 
> 

So, It will remain the same in small screen devices? Or You can fix that?

**Comment by HimanshuNarware** [comment]
> > > I can't see any difference in the scroll bar on my mobile device. Please Check
> > 
> > 
> > @Souravvmishra  I think is because of the small screen
> > 
> 
> So, It will remain the same in small screen devices? Or You can fix that?

it will remain the same in the small device. because the screen size is small

**Comment by Spyware007** [comment]
@HimanshuNarware Thank you so much!
@Souravvmishra  I guess its because of the dev tools!
It will show perfectly in mobile, let's merge and see!

**Pull request merged**
