### PR TITLE
add another button

### PR DESCRIPTION
**Pull request by akshaysoni10**

### CODE REVIEW

**Comment by Spyware007** [comment]
Hello @akshaysoni10 Please rename the css file to style.css

**Comment by akshaysoni10** [comment]
Ok

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by PoorviShetty** [comment]
@akshaysoni10 There seems to be a merge conflict, please resolve it

**Pull request merged**
