### PR TITLE
created cool Like Button

### PR DESCRIPTION
**Pull request by abhi03ruchi**
Created a cool-like button which changes to heart on hover.
Plz review and merge.

https://github.com/Spyware007/Animating-Buttons/assets/105661636/876ecfdb-6bee-4e80-a10e-ad375e26a240

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by abhi03ruchi** [comment]
I have resolved conflicts plz merge in. @PoorviShetty

**Comment by PoorviShetty** [comment]
Hey, please check again

**Comment by abhi03ruchi** [comment]
I am unable to click on  resolve conflict now 🥲 , shall I create a new pr for my button? 
https://github.com/Spyware007/Animating-Buttons/assets/105661636/89135479-afc2-440c-9179-f9ba307c9901

**Comment by PoorviShetty** [comment]
> @PoorviShetty, @Spyware007, I am unable to click on resolve conflict now 🥲 , shall I create a new pr for my button? [](https://github.com/Spyware007/Animating-Buttons/assets/105661636/89135479-afc2-440c-9179-f9ba307c9901)

Yes, go ahead!

**Pull request closed without merging**
