### PR TITLE
Added A like btn with cool hover effect

### PR DESCRIPTION
**Pull request by abhi03ruchi**
## Fixes Issue

Closes #692  

## Changes proposed
Created a cool-like button which changes to heart on hover.
Plz review and merge.

## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/105661636/876ecfdb-6bee-4e80-a10e-ad375e26a240

## Checklist

- [ ] You've linked this PR to the correct issue.
- [ ] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please resolve merge conflicts

**Comment by abhi03ruchi** [comment]
I am again getting this now, 🥲. When I created the pr yesterday, all merge conflicts were resolved. I don't know why this is happening. Plz help.  
e98ed053-b0eb-4b39-9364-76579ee8df30

**Comment by PoorviShetty** [comment]
Resolve merge conflicts in your local, that should work

**Comment by abhi03ruchi** [comment]
> Resolve merge conflicts in your local, that should work

Plz merge now.

**Comment by TANYA-CHAN** [comment]
Could you please reupload your file because there seem to be 221 file changes

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by abhi03ruchi** [comment]
@TANYA-CHAN @Spyware007  , I have created a new pr #1374 , plz merge it .

**Pull request closed without merging**
