### PR TITLE
ADD: ANIMATED CHECKMARK BUTTON ✨

### LINKED ISSUE #1141: 💡 [ADD]: ANIMATED CHECKMARK BUTTON
### Details

- This issue is about adding animated checkmark button
- The button's checkmark will be checked with a nice animation once the user clicks the button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/92252895/15726e2d-1b16-411b-b019-66e300de0197

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue

Closes #1141 

## Changes proposed
- This PR is about adding Animated Checkmark Button
- The button's checkmark will be checked with a nice animation once the user clicks the button

## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/92252895/15726e2d-1b16-411b-b019-66e300de0197

## Checklist
- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Please verify this PR @Spyware007

**Comment by 0xabdulkhalid** [comment]
Hey guys @Spyware007  ,@TANYA-CHAN, @PoorviShetty  

All conflicts are resolved please merge this PR as soon as possible, i want to do more contributions <3

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by 0xabdulkhalid** [comment]
Yeah sure @Spyware007, but today is 19 June.

And this PR is already been opened and ready to merge without any conflicts.

Please merge this PR Bro.

**Review by adity2911 — APPROVED** [review]

**Pull request merged**
