### PR TITLE
Animating play button

### PR DESCRIPTION
**Pull request by ManaswiKasiraju**
## Fixes Issue

#646 

## Changes proposed
Created a pulsating play button.

## Screenshots
Screenshot (218)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by ManaswiKasiraju** [comment]
Hi @PoorviShetty may I know what I am left with. Should I remove the changes in any files? May I know which file shouldn't be changed?

**Comment by PoorviShetty** [comment]
Please do not modify files in src folder other than Data.js, and please look into the additional Data.js you have created outside src folder

**Comment by ManaswiKasiraju** [comment]
Hi @PoorviShetty I deleted the extra Data.js file and removed all other extra changes I made. Please merge my contribution.

**Comment by Souravvmishra** [comment]
Fix the conflicts

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by ManaswiKasiraju** [comment]
> Fix the conflicts

I resolved the conflicts.

**Comment by ManaswiKasiraju** [comment]
> Fix the conflicts

I resolved the conflicts in data.js

**Comment by ManaswiKasiraju** [comment]
please merge my pull request if there aren't any issues.

**Pull request merged**
