### PR TITLE
Added social-icon-button issue#479

### PR DESCRIPTION
**Pull request by Ks103**
Updated changes in Data.js as showing conflicts also , I resolved them
Please verify and I request you to merge my pr after verifying.

### CODE REVIEW

**Comment by Ks103** [comment]
I changed all files and updated data.js also , request you to please verify and merge my pr @PoorviShetty @Spyware007

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by Ks103** [comment]
Conflict resolved

**Comment by Ks103** [comment]
Can you please tell me how these checks be green tick

**Comment by Spyware007** [comment]
@Ks103 That was Vercel's issue!
I will fix it dw!

Looking forward to more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Comment by Ks103** [comment]
Thankyou @Spyware007

**Pull request merged**
