### PR TITLE
Cards

### PR DESCRIPTION
**Pull request by ombhojane**
Hey, I have changed the design of social media buttons. Background colour is changed to respective social media site's theme colour. Also added a fade animation when we hover on text. Please review and let me know for any changes.

New Design : 
image

Preview: 
https://drive.google.com/file/d/10Eoxwz0iNmImZV4UjbYq7gADKUP0tSA-/view?usp=share_link

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by ombhojane** [comment]
Hey @PoorviShetty 
I've updated Package-lock.json again, how can I deploy it in vercel again? Is it done from your side?

**Comment by ombhojane** [comment]
I have fixed issue in PR #624

**Comment by Spyware007** [comment]
@ombhojane closes #624 

I don't think your changes are valid.
Also changing the button on the landing may affect the button in the explore section.

**Pull request closed without merging**
