### PR TITLE
button added

### LINKED ISSUE #1285: Adding a new button
### Details

I would like to add a new button palette.

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by shruuti321**
## Fixes Issue

Closes #1285

A new button palette is added
## Screenshots

image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by Souravvmishra** [comment]
Fix The Merge Conflicts

**Comment by shruuti321** [comment]
Done

**Comment by TANYA-CHAN** [comment]
Please remove the shr-ney file at the very top and reupload

**Comment by shruuti321** [comment]
Delete from where?Shall I create a new pull request?

**Comment by TANYA-CHAN** [comment]
> Delete from where?Shall I create a new pull request?

 I think either you can reuplaod and the changes will reflect here only or create a new PR, whichever works for you

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by shruuti321** [comment]
> > Delete from where?Shall I create a new pull request?
> 
> I think either you can reuplaod and the changes will reflect here only or create a new PR, whichever works for you

Okay so I have created a new pull request. Kindly close this one and accept the other

**Pull request closed without merging**
