### PR TITLE
Added lazy loading to images

### LINKED ISSUE #1569: [Improve] Optimize Performance by Adding Lazy Loading to Image Tags
### Details

As part of optimizing the project's performance, we need to implement lazy loading for the tags used throughout the project. Lazy loading is a technique that defers the loading of images until they are about to be displayed on the user's screen, reducing the initial load time and improving the overall user experience.

To accomplish this, we need to modify the existing tags and add the loading attribute with the value of "lazy". This attribute instructs the browser to delay the loading of the image until it becomes visible within the viewport.

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Avinash905**
## Fixes Issue

Closes #1569 

## Changes proposed

Added lazy loading attribute to all image tags to improve performance of the website

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
@Avinash905 Sorry for the delay!
Can you please solve the merge conflicts?

**Comment by adity2911** [comment]
Is there any visual difference because of this?

**Comment by adity2911** [comment]
Can you describe the changes made to the website?

**Comment by Avinash905** [comment]
> Can you describe the changes made to the website?

When the page loads, the browser will prioritize the loading of visible content. As the user scrolls down or the image enters the viewport, the browser will automatically start fetching and displaying the actual image specified in the src attribute. This way, images that are not immediately visible to the user will be loaded later, conserving bandwidth and improving the page's initial loading speed.

**Comment by adity2911** [comment]
@Spyware007 @Souravvmishra Please check whether the feature is required or not

**Comment by Souravvmishra** [comment]
@Spyware007 This Seems Fine

**Comment by Souravvmishra** [comment]
@Avinash905 Thank You Buddy

**Pull request merged**
