### PR TITLE
Neon Glass Button

### LINKED ISSUE #1133: [Add] NEON GLASS BUTTON
### Details

Willing to add a Neon Glass Button to the website. Video below :-

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/100849696/9166f391-363b-4ae5-8a64-1f0699fc54eb

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## Fixes Issue

Closes #1133 

## Changes proposed
Added a Neon Glass Button

## Screenshots
image

## Checklist

- [X] You've linked this PR to the correct issue.
- [X] You have checked that the code is working correctly.
- [X] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by sabhisharma-ise** [comment]
@Spyware007 hey, will my pr gonna merge as i have sent them before 20 June only!

**Comment by adity2911** [comment]
check the data.js file. The data of others were compromised. revert the changes for us to approve the PR.

**Comment by sabhisharma-ise** [comment]
@adity2911 Hey, sorry about it. I've tried my best to retrieve the latest data and then again pushed my changes on it!
Can you please check now!

**Pull request merged**
