### PR TITLE
Added a new button

### PR DESCRIPTION
**Pull request by Guli93**
completed #836 

Screenshot (143)

### CODE REVIEW

**Comment by Guli93** [comment]
> Hi, there seems to be a merge conflict, please resolve it

@PoorviShetty  Hey,I resolved it.

**Comment by PoorviShetty** [comment]
Can you please check again?

**Comment by Guli93** [comment]
> Can you please check again?  
  There r no more conflicts now

**Comment by Guli93** [comment]
> > Can you please check again?
> > There r no more conflicts now

Hey!! @PoorviShetty there seems to be no more conflicts now.

**Pull request merged**
