### PR TITLE
Added a button with hover animations using JavaScript

### PR DESCRIPTION
**Pull request by amrit2611**
I added the animation.js file in the same folder with the index.html and style.css files. 
Kindly check it out.

### CODE REVIEW

**Comment by Spyware007** [comment]
Please rename your animation.js to app.js

**Comment by amrit2611** [comment]
> Please rename your animation.js to app.js

Yes sure

**Comment by Spyware007** [comment]
Thank you for your contribution.🤩
I hope you like it.
Please 🌟 the repo.
@amrit2611

**Comment by amrit2611** [comment]
> Thank you for your contribution.🤩 I hope you like it. Please 🌟 the repo. @amrit2611

Thanks @Spyware007

**Pull request merged**
