### PR TITLE
Added subscribe button

### LINKED ISSUE #1230: [Add] <Create a unique subscribe button with exquisite animations>
### Details

Create a unique subscribe button with exquisite animations

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Fixes Issue

Closes #1230 

## Changes proposed

Added a new button

## Screenshots

Button preview:

https://github.com/Spyware007/Animating-Buttons/assets/95973644/18788981-bf9f-4f4c-803f-6aaddf87fe98

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by karthiknadar1204** [comment]
@Spyware007 I submitted the the pr on 20th, last day for submission, please accept it

**Comment by adity2911** [comment]
DID you check #1346 ?

**Comment by adity2911** [comment]
you need to add data to  data.js also

**Comment by karthiknadar1204** [comment]
@adity2911 I added the js code in <script>tag inside the html, will change and update it today itself, will it still be accepted though

**Comment by karthiknadar1204** [comment]
@Spyware007 @adity2911 Updating the codebase and pushing the third file in a bit , so please consider the pr

**Comment by adity2911** [comment]
Try to make the changes asap

**Comment by adity2911** [comment]
you still have to update the data.js

**Comment by karthiknadar1204** [comment]
Hey where to add ths js code, like in Data.js file, there are names like the githu username

**Comment by karthiknadar1204** [comment]
done, pushing the changes

**Comment by karthiknadar1204** [comment]
@Spyware007 @adity2911 Had to open a second pr, couldn't pull the changes successfully so cloned the repo again and made the changes accurately, please refer the pr #1495 , subset of this pr, please consider it , have worked hard

**Comment by karthiknadar1204** [comment]
The same button has been added

**Comment by adity2911** [comment]
close this pr then

**Comment by adity2911** [comment]
the other PR will be considered for merge

**Pull request merged**
