### PR TITLE
add a animated button

### PR DESCRIPTION
**Pull request by An525ish**

### CODE REVIEW

**Comment by Spyware007** [comment]
@An525ish looks like you removed this username from the Data.js -> dassoumen98_1
Please add this and it will get merged.

**Comment by An525ish** [comment]
> @An525ish looks like you removed this username from the Data.js -> dassoumen98_1 Please add this and it will get merged.

I have added my name there too...so shall I leave it or remove it

**Comment by Spyware007** [comment]
@An525ish Both names should be there!

**Comment by Spyware007** [comment]
Screenshot 2023-05-23 at 12 03 25 AM

Looks like you removed 2 more buttons 
See on the left-hand side the minus indicates that you had removed that line of code and the right-hand side is the final code!
Are you facing any issues here?

**Comment by An525ish** [comment]
> Screenshot 2023-05-23 at 12 03 25 AM
> Looks like you removed 2 more buttons See on the left-hand side the minus indicates that you had removed that line of code and the right-hand side is the final code! Are you facing any issues here?

Sorry I missed some conflicts...let me fix it

**Comment by Spyware007** [comment]
@An525ish Okay sure!
Just relax and be calm!

**Comment by An525ish** [comment]
why is it not getting deployed..?

**Comment by Spyware007** [comment]
I guess you are not updating the branch as other PRs getting merged.
You should always update your forked branch!

**Comment by Spyware007** [comment]
@An525ish That was a hectic task?
But amazing work! Looking forward to more contributions from you.

Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Comment by An525ish** [comment]
okkay looks like everything is fine this time...😮‍💨

**Pull request merged**
