### PR TITLE
Added Neuromorphism button 

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, @Spyware007 I have added a beautiful neuromorphism button to your website. Please review my pr and merge it. Thank you!

Issue no:- #322 

Screenshot:-
Screenshot (766)

### CODE REVIEW

**Comment by sumitkr2000** [comment]
hey @PoorviShetty @Spyware007 please look into this pr. Thank you!

**Comment by sumitkr2000** [comment]
hey @PoorviShetty @Spyware007 please look into this pr. Thank you!

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by sumitkr2000** [comment]
Okay! @PoorviShetty

**Comment by sumitkr2000** [comment]
Hey, @PoorviShetty Now I have resolved the merge conflict. Please merge my pr.

**Comment by sumitkr2000** [comment]
@Spyware007 @PoorviShetty Please merge my pr

**Comment by PoorviShetty** [comment]
@sumitkr2000 Please don't modify package-lock.json

**Comment by sumitkr2000** [comment]
Okay, I am creating another pr. This is messed up now.

**Pull request closed without merging**
