### PR TITLE
New animated button.

### PR DESCRIPTION
**Pull request by masked-wolf18**
Added new button.

### CODE REVIEW

**Comment by Spyware007** [comment]
@masked-wolf18 You forgot to add the contents in the Data.js file.

**Comment by masked-wolf18** [comment]
I have updated Data.js

**Comment by Spyware007** [comment]
Screenshot 2023-05-23 at 11 44 03 PM

Your buttons are looking like this!
Please look into it. 😅

**Comment by Spyware007** [comment]
@masked-wolf18 Are you working on the fixes?

**Comment by Spyware007** [comment]
@masked-wolf18 I fixed it!
Looking forward to more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
