### PR TITLE
Updated The Created By Button as well as the Download Button

### PR DESCRIPTION
**Pull request by Souravvmishra**
Updated the created by tbtton to add more colors and effects. 
Added the icon of user before the text.
Animated Buttons — Mozilla Firefox 21-05-2023 16_42_27

Added the functionality to go the github of the creator by clicking the button.
Updated the download button to add more focus to it. added some extra effects.

### CODE REVIEW

**Comment by Souravvmishra** [comment]
A better way would be to move the createdBy tag to the top right of the card as a small alert like thing. currently its taking a huge portion of the user focus.

**Comment by Souravvmishra** [comment]
Heyy @Spyware007 

Everything seems to be **fine** now. Have a look & let me know if there is any fault.

**Comment by Spyware007** [comment]
Cool! @Souravvmishra .
You are doing a great job.

Looking forward to more contributions from you! 🧑‍💻
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Comment by Souravvmishra** [comment]
Towards Greatness Brother ⚡

**Pull request merged**
