### PR TITLE
Added Neuromorphism button

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, @Spyware007 I have added the neuromorphism button to your awesome repo. Please review my pr and merge it. Thank you!

Issue no. #322 

- Screenshot:- 

241245504-d4133bf0-696c-4b4c-b109-37d728ea0de8

### CODE REVIEW

**Comment by sumitkr2000** [comment]
Hey @PoorviShetty @Spyware007 Please merge my pr

**Comment by PoorviShetty** [comment]
Hey, please do not change others' buttons, try taking a fresh pull

**Comment by sumitkr2000** [comment]
Yes, I took a fresh pull clone and did changes, and then created the pr. I have not changed any other buttons. I was confused for an hour because you have not updated your website. Later I realized that your data and my data files are the same then I reopened the pull request.

**Comment by sumitkr2000** [comment]
@Spyware007 @PoorviShetty Please merge my pr after reviewing it.

**Comment by PoorviShetty** [comment]
> Yes, I took a fresh pull clone and did changes, and then created the pr. I have not changed any other buttons. I was confused for an hour because you have not updated your website. Later I realized that your data and my data files are the same then I reopened the pull request.

You have changed 28 files, please look into it

**Comment by sumitkr2000** [comment]
When I was cloning I ran into error so I downloaded the zip file and then started working on it. I don't know how all the files got changed. Let me fix it again :)

**Pull request closed without merging**
