### PR TITLE
feat: nav bar theme feature 🚀✨ 

### LINKED ISSUE #1695: [FEAT]: ADD NAV BAR THEME FOR WEBSITE 💡
### Details

- The new feature is about introducing a theme color for the navigational bars of devices (browser's theme are overriden)
- The usage of providing a theme color in the meta tag for HTML allows you to define the color that will be used as the browser's theme color when a user visits your website. The theme color is displayed in the browser's UI elements such as the address bar, tabs, and task switcher.
-  Branding: You can use your brand's primary color or a color that aligns with your website's design to reinforce your brand identity. This can create a consistent and recognizable experience for users across different platforms.
- User experience: By setting a theme color that matches your website's design, you can provide a cohesive and immersive user experience. The theme color can seamlessly integrate the browser UI with your website's color scheme, enhancing visual continuity.
- Visual appeal: A well-chosen theme color can make your website stand out and make a positive impression on users. It adds a touch of personalization and professionalism to the browsing experience.
- Accessibility: The theme color can also contribute to accessibility considerations. By selecting a color with sufficient contrast against the browser UI elements, you can improve readability and ensure that the UI remains legible for users with visual impairments.
- The primary theme color of this site is two colors
  - `#151515`
  - `#72ebeb`
- The colors can be switched on the nav-bar like the body when switching the mode to light and dark

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue

Closes #1695 

## Changes proposed
- Added Browser nav bar feature for Animating Buttons Website
- This feature is in beta stage for all of the major browsers like Firefox, Chrome.
- But for now it can finely work on Mobile Chrome, Safari & Vivaldi Etc.
- The screenshots are taken on Vivaldi Browser for demonstration.

## Screenshots

||SAMPLES FROM TWO PAGES|
|:---:|:----:|
| **HOME**| home|
| **ABOUT**| about|

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
## Note to reviewers 📌 
- This change is comes under adding a new feature on existing code, So make sure to add `level2` for this PR during Merge.
- Thank you!

**Comment by Souravvmishra** [comment]
@0xabdulkhalid How can i preview this? there is no difference in my browsers

**Comment by Souravvmishra** [comment]
Also if it works, can you reduce a little lower color as compared to main color

**Comment by 0xabdulkhalid** [comment]
If we reduce the color then we can't get the realistic theme effect @Souravvmishra

**Comment by 0xabdulkhalid** [comment]
> @0xabdulkhalid How can i preview this? there is no difference in my browsers

I already mentioned about this on PR comment's `Changes Proposed` section.
This feature is still in development for common browsers like Firefox, Chrome.

You can use Mobile Chrome (you want to disable dark theme for that), For desktop you can use Vivaldi.

**Comment by 0xabdulkhalid** [comment]
> @0xabdulkhalid How can i preview this? there is no difference in my browsers

@Souravvmishra I already mentioned about this on PR comment's `Changes Proposed` section.
This feature is still in development for common browsers like Firefox, Chrome. So it won't work for these browsers.

But it can work at browsers like Vivaldi, Chrome for Mobile (you want to disable dark mode for that) Etc.

**Comment by Souravvmishra** [comment]
No difference 
@Spyware007 Can You See Any Difference
Have a Look

**Comment by 0xabdulkhalid** [comment]
Screenshot_20230802_121325
Screenshot_20230802_121441

## @Souravvmishra 🙂

**Comment by 0xabdulkhalid** [comment]
# @Souravvmishra 🙂

|||
|:---:|:----:|
|Screenshot_20230802_121325 | Screenshot_20230802_121441 |

**Comment by 0xabdulkhalid** [comment]
# @Souravvmishra, @Spyware007 🙂

|||
|:---:|:----:|
|Screenshot_20230802_121325 | Screenshot_20230802_121441 |

**Comment by Souravvmishra** [comment]
Please Don't Spam
Om is a little busy. He'll look into this asap

**Comment by Spyware007** [comment]
@0xabdulkhalid I am not able to see any difference.
Could you explain what are you trying to say?

**Comment by 0xabdulkhalid** [comment]
@Spyware007 in what browser you testing this feature ?

If you're in Chrome for Mobile then you need to Enable `Light` mode in Theme.

And i already mentioned that "*This feature is still in development for common browsers like Firefox, Chrome. So it won't work for these browsers. But it can work at browsers like Vivaldi, Chrome for Mobile (you want to disable dark mode for that) Etc."*

**Comment by 0xabdulkhalid** [comment]
Is anyone here @Souravvmishra, @Spyware007 ?

Contributing period is about coming to an end, Please merge this PR soon.

**Pull request closed without merging**
