### PR TITLE
Redesign the Created By, Show Code and Download buttons.

### PR DESCRIPTION
**Pull request by dellarocca99**
Hello dear @Spyware007. 
I redesigned the buttons as you asked.
Note the following: if you want the three buttons in the same line, the length of the line will be limiting long usernames.
Another option would be just leaving the "Created By" button on top, and the "Show Code" and "Download" buttons in the bottom row. If you prefer this, let me know and I can change it.
Hope you like it!

### CODE REVIEW

**Comment by Spyware007** [comment]
@dellarocca99 Please fix the merge conflicts and it will be merged asap on priority.

**Comment by Spyware007** [comment]
@Souravvmishra Can you check this, I mean If it's not breaking your code or not?

**Comment by dellarocca99** [comment]
@Spyware007 I only left the option to download as .zip, as in the requirements of the issue didn't mention any extra button. If needed I can add it :)

**Comment by Spyware007** [comment]
@dellarocca99 The functionality is already added just please add the buttons in your UI!

**Comment by Spyware007** [comment]
@dellarocca99 I mean check the latest version and add the buttons like there is an additional button to get a zip of the button code!

**Comment by dellarocca99** [comment]
Ok I will!

**Comment by dellarocca99** [comment]
Hi @Spyware007 ! Whenever you can, take a look at the new design of the buttons and let me know if you're ok with it. 
Up to now there are no conflicts with the base branch. I didn't put user, show code, download files and download as zip buttons all in the same line because it won't fit.

**Comment by Spyware007** [comment]
@dellarocca99 Thank you so much for your contribution!
Star ✨ the repo if you like it! 🚀🤩

**Pull request merged**
