### PR TITLE
updated navbar and add new button

### PR DESCRIPTION
**Pull request by shivang-16**
Added a new animated button and add  a rotation effect on gdsc logo in navbar
Screenshot 2023-06-01 155342

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by shivang-16** [comment]
how to resolve conflict can you please tell..

**Comment by TANYA-CHAN** [comment]
Add your name in the Data.js please along with the number of buttons you've added as written in the ReadMe

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Closing this as can't fixed!
Please create another PR, I will tell the instructions asap.

**Pull request closed without merging**
