### PR TITLE
Added Cartoon Animated Button

### LINKED ISSUE #1432: [Add] CUSTOM ANIMATED CARTOON Button
### Details

i want to add a CUSTOM ANIMATED CARTOON Button

https://github.com/Spyware007/Animating-Buttons/assets/119161467/c406aa1b-4397-446f-8beb-ff97bbeb6c32

### Screenshots

image

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by lakhan06**
## Fixes Issue

Closes #1432 

## Changes proposed
 want to add a CUSTOM ANIMATED CARTOON Button .

https://github.com/Spyware007/Animating-Buttons/assets/119161467/367ab3a4-25ea-4a79-b73e-8f64d398d18e

## Screenshots
image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers
@TANYA-CHAN  @Souravvmishra  there are some errors in data.js file so i corrected them and also add my new buttons so i kindly request your attention and consideration in reviewing and accepting my pull request . I would greatly appreciate it if you could allocate some time to review the Pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

### CODE REVIEW

**Comment by lakhan06** [comment]
> > @TANYA-CHAN Their are some errors in data.js you can check it and I corrected these errors .You can check
> 
> Sure, I'll take a look but it can be merged only after tmrw I think so please wait :)

okay no worry Thanks

**Comment by lakhan06** [comment]
@adity2911  Please merge my pull request

**Comment by lakhan06** [comment]
@Spyware007 Please merge my pull request if possible it will be very helpfull for me to move forward in the program

**Comment by lakhan06** [comment]
@Souravvmishra Please merge my pull request if possible it will be very helpfull for me to move forward in the program

**Comment by Souravvmishra** [comment]
Conflicts

**Comment by lakhan06** [comment]
@Souravvmishra I  resolved the issues

**Pull request merged**
