### PR TITLE
New Animation To the Submit Button Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## Fixes Issue

#1305 

## Changes proposed

New Animation To the Submit Button added

## Video

https://github.com/Spyware007/Animating-Buttons/assets/114821855/e06f9a98-a8fb-4843-8304-ee2034e3d7c7

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
@TANYA-CHAN

**Comment by TANYA-CHAN** [comment]
> @TANYA-CHAN

Please remove extra files quickly, if stuck look into ReadMe

**Comment by Kalivarapubindusree** [comment]
no Extra files those are 2 separate animated buttons 
[1_pr](https://github.com/Spyware007/Animating-Buttons/pull/1378)
[2_pr](https://github.com/Spyware007/Animating-Buttons/pull/1301)

**Comment by TANYA-CHAN** [comment]
> @TANYA-CHAN Their is No Extra files those are 2 separate animated buttons [1_pr](https://github.com/Spyware007/Animating-Buttons/pull/1378) [2_pr](https://github.com/Spyware007/Animating-Buttons/pull/1301)

You cannot upload different buttons and issues in one PR, they are different issues please create different PRs for them. The buttons seem amazing but you will have to oblige with this for me to merge :)

**Comment by Kalivarapubindusree** [comment]
Okay I will do separate PRs of them and I will tag You in those PRs as well!

**Pull request merged**
