### PR TITLE
Random Quote generator

### PR DESCRIPTION
**Pull request by VardaPanchal005**
Random quote generator.
#GSSOC 23

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please refer Readme for file naming conventions

**Comment by PoorviShetty** [comment]
Yes you do, please make new commits with corrections

**Comment by VardaPanchal005** [comment]
Just this one or all of them ?

**Comment by PoorviShetty** [comment]
Please create a fresh PR after going through the Readme, and remove the files that do not follow the conventions

**Comment by VardaPanchal005** [comment]
Yes I'm creating a new pr

**Pull request closed without merging**
