### PR TITLE
Button#2

### PR DESCRIPTION
**Pull request by abhishekkhairnar**
after resolving all conflicts added my second contribution

### CODE REVIEW

**Comment by Arjun-Ingole** [comment]
image
Buttons seems broken, Get rid of three instances of the same button

**Comment by Arjun-Ingole** [comment]
image
Rather than fixing the button it seems you've add another broken button, Please fix these issues and Tag me once done

**Comment by abhishekkhairnar** [comment]
@Arjun-Ingole i have deleted new button now could you please check it again

**Comment by abhishekkhairnar** [comment]
@Arjun-Ingole buttons are fixed can you check it now

**Comment by Arjun-Ingole** [comment]
Everything seems fine this time, Merging Under issue #1

**Pull request merged**
