### PR TITLE
update button

### LINKED ISSUE #1220: Improve buttons Style
### Details

Hi, @Spyware007, I am a contributor in gssoc'23.
I want to work on updating styles of button I've added.
please assign me this task under label gssoc'23

### Screenshots

_No response_

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Ayush9951**
close #1220
Hi @PoorviShetty , I've Improve the alignment of buttons, please check

### CODE REVIEW

**Comment by Souravvmishra** [comment]
Fix the Merge Conflicts

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Ayush9951** [comment]
Hi @Souravvmishra, I've resolved the merge conflicts, please check

**Comment by Souravvmishra** [comment]
Add your name either to the very first or very last in data.js

**Comment by Ayush9951** [comment]
Hi @PoorviShetty, @Souravvmishra , please consider merging the pull request

**Review by adity2911 — APPROVED** [review]

**Pull request merged**
