### PR TITLE
fixes #546

### LINKED ISSUE #546: bug: wrong GitHub username displayed by JS alert dialog box
image

**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Problem:** I have solved 3 issues and created 3 branches and files for each issue by the name ```hashfx_1```, ```hashfx_2```, ```hashfx_3```. When these files are deployed and clicked, it shows my GitHub as ```https://github.com/hashfx_3``` instead of ```https://github.com/hashfx```.

**Suggestion:** Data.js could ask for an optional parameter viz. GitHub user-name. Last data to the items of ```Data.js``` object should be GitHub user-name in case of multiple commits at once.

### PR DESCRIPTION
**Pull request by hashfx**
fixes #546 
You could consider this fix under GSSOC' 23 contribution

A request to contributors to kindly adhere to Contribution guide and maintain directory names for **username** as ```username_1```, ```username_2``` and not ```username1``` or ```username-2```

### CODE REVIEW

**Comment by Spyware007** [comment]
@hashfx Can please you fix the merge conflicts?

**Comment by Souravvmishra** [comment]
let githubUsername = username.split("_")[0]; This will produce unexpected behavior if the username in such a way like . '
name_otherName_[number]. Try Improving the logic in such a way instead of getting the name, you simply remove the end number. but again you have to make sure, if the number is a part of username, it should not get removed.

**Comment by hashfx** [comment]
> let githubUsername = username.split("_")[0]; This will produce unexpected behavior if the username in such a way like . ' name_otherName_[number]. Try Improving the logic in such a way instead of getting the name, you simply remove the end number. but again you have to make sure, if the number is a part of username, it should not get removed.

GitHub seems very unlikely to allow underscores, because DNS labels containing underscores are not valid Internet hostnames.

**Comment by hashfx** [comment]
@Spyware007 Can you kindly review this PR ASAP. It affects ```main.jsx```.

**Comment by TANYA-CHAN** [comment]
These kinds of merges will be closed after tmrw :)

**Comment by Souravvmishra** [comment]
@Spyware007 Have look

**Pull request closed without merging**
