### PR TITLE
A new button was added.

### PR DESCRIPTION
**Pull request by youraj-08**
## Description

The steps outlined in the project's README have been diligently followed to ensure proper setup and configuration.

**Addition of a New Button:** This pull request introduces a new button to the existing list of buttons in the user interface. 

These changes have been carefully implemented and tested to ensure they integrate seamlessly into the existing codebase. The new button complements the existing functionality and adheres to the project's design principles.

## Preview
**Screenshots:** 

Screenshot (13)

Screenshot (14)

### CODE REVIEW

**Comment by youraj-08** [comment]
The merge conflict is resolved.

**Comment by PoorviShetty** [comment]
Hey, please check again

**Comment by youraj-08** [comment]
> Hi, are you still working on this?

I have been out due to some urgent issues. I will fix it before this week ends. Sorry for the inconvenience.

**Review by TANYA-CHAN — APPROVED** [review]

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Closing this as invalid!

**Pull request closed without merging**
