### PR TITLE
Implemented an Animated Delete Button for Enhanced User Experience

### LINKED ISSUE #919: Implementing an Animated Delete Button for Enhanced User Experience
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
**Description**
As part of GSSOC (GirlScript Summer of Code), I aim to implement a delete button functionality that provides a visually appealing and interactive experience for users. When the delete button is clicked, it will remove all occurrences of the word "delete" and visually animate them into a dustbin icon.

### Problem Statement
Currently, our application lacks a user-friendly way to remove instances of the word "delete." Users often have to manually edit the text or use alternative workarounds, which can be time-consuming and tedious.

### Proposed Solution
Introducing a delete button that streamlines the process of removing the word "delete" from the text. Clicking the button will automatically replace all instances of the word with a dustbin icon, creating a fun and interactive visual representation of the deletion action.

### Requirements
To address this issue, the following requirements need to be fulfilled:
- Implement a delete button with an appropriate visual representation, such as a trash can or dustbin icon.
- Detect all occurrences of the word "delete" in the text and replace them with the chosen visual representation.
- Apply smooth and visually pleasing animation effects to transition the word "delete" into the dustbin icon.
- Ensure that the delete functionality is accessible and works reliably across different browsers and devices.

Please assign this issue to me under GSSOC'23 (GirlScript Summer of Code).
WhatsApp Image 2023-06-03 at 4 06 22 PM

### PR DESCRIPTION
**Pull request by Nishusk**
## Fixes Issue

Closes #919

## Changes proposed

Implemented an animated delete button functionality that allows users to remove instances of the word "delete" and visually animate them into a dustbin icon. The button component has been added with appropriate styling and animation effects. The logic detects all occurrences of the word "delete" and replaces them with the dustbin icon.

## Screenshots
WhatsApp Image 2023-06-03 at 4 06 22 PM

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers

Thank you for taking the time to review this pull request. Here are a few things I'd like to highlight:

- Please pay attention to the `deleteButton.js` file where the delete button logic is implemented.
- I faced some challenges with handling keyboard accessibility, so any feedback in that area would be greatly appreciated.
- If you have any suggestions for improving the animation effects or overall code structure, I'm open to feedback.

Once again, thank you for your valuable time .

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please make sure all your button folders follow the naming convention, and please do not add buttons to the src folder

**Comment by Nishusk** [comment]
> Please make sure all your button folders follow the naming convention, and please do not add buttons to the src folder
Dear Ma'am,
Thank you for your message. I appreciate your instructions regarding the folder naming convention and not adding buttons to the src folder. However, I would like to kindly point out that according to the readme file provided, it explicitly states that we are required to add the buttons to the src folder.

Here are the steps mentioned in the readme file:

Go to the public/Buttons folder in the repository.
Add a new folder with your GitHub username, including your button code (index.html + style.css files).
Go to the src/Data.js file.
Add your folder name (e.g., github_username) and your code in the src/Data.js file.
I apologize for any confusion caused, but I believe it is necessary to follow the instructions as stated in the readme file. If there have been any recent updates or changes to the process, please let me know, and I will be happy to adapt accordingly.

Thank you for your understanding.

**Comment by PoorviShetty** [comment]
Please explain how the 'metallic_button" folder follows the naming convention and do not add buttons to the src folder, you're only required to modify Data.js

**Comment by Nishusk** [comment]
Thank you for bringing to my attention the issue regarding the
"metallic_button" folder and the naming convention in the open source
project. I apologize for the oversight and any inconvenience caused. Allow
me to provide a detailed explanation of the situation and the actions I
have taken to rectify it.

Upon reviewing the project's readme file and guidelines, I realized that I
had inadvertently violated the naming convention by creating the
"metallic_button" folder. Recognizing my mistake, I promptly took
corrective measures to address the issue. Specifically, I made the
following changes:

1. Removal of the "metallic_button" folder: I deleted the "metallic_button"
folder from my branch to adhere to the prescribed naming convention.

2. Creation of a new folder with my username: To rectify the naming
convention violation, I created a new folder using my username as per the
project's guidelines. This new folder serves the same purpose as the
previous "metallic_button" folder.

3. Update in data.js file: Additionally, I made the necessary modifications
in the "data.js" file within the "src" folder to reflect the changes in
folder structure and ensure consistency with the project requirements.
These updates ensure that the metallic button functionality is correctly
integrated and aligned with the project's scope.

Regarding the conflict that occurred during the pull request, I carefully
resolved it by incorporating the necessary changes and ensuring that the
branch is up to date with the main project repository. However, it appears
that the conflict resolution is not reflecting in the pull request section.

Once again, I sincerely apologize for any inconvenience caused by the
initial mistake. I am fully committed to adhering to the project's
guidelines and ensuring the smooth integration of my contributions. Please
be assured that I am taking the necessary steps to rectify the situation
promptly.

If you have any further questions, concerns, or guidance, please do not
hesitate to let me know. I greatly appreciate your understanding and
support throughout this process.

Thank you for your attention to this matter.

Best regards,
Nishu kumari (GSSOC'23)

**Comment by PoorviShetty** [comment]
Please check 'components/Glass_Buttons' folder, I don't think it should be included in this PR
And please resolve merge conflicts with package-lock.json

**Comment by Nishusk** [comment]
> I have removed the unnecessary files from my branch; however, I noticed that the changes are not reflecting in the repository.Thank you for your attention to this matter.

**Comment by TANYA-CHAN** [comment]
Reupload only your button please

**Comment by Nishusk** [comment]
> Reupload only your button please

Ma'am, I apologize for any confusion. I will reupload only the button files as per your request. Thank you for clarifying.

**Comment by Spyware007** [comment]
# Please check #1346

**Pull request merged**
