### PR TITLE
Added ripple effect button

### PR DESCRIPTION
**Pull request by ganraj21**
This is awesome effect

### CODE REVIEW

**Comment by Spyware007** [comment]
@ganraj21 Please fix the merge conflicts.

**Comment by ganraj21** [comment]
but how to fix this conflicts @Spyware007

**Comment by Spyware007** [comment]
Just sync your repo with the main branch and add your code again.
Or if possible follow the entire process again.

**Comment by ganraj21** [comment]
Now conflict solved @Spyware007

**Comment by Spyware007** [comment]
@ganraj21  I think you should do the entire thing from the start.

**Comment by ganraj21** [comment]
yes ok

**Pull request closed without merging**
