### PR TITLE
Adding new button animations click rotate.

### PR DESCRIPTION
**Pull request by rcode321**

### CODE REVIEW

**Comment by Spyware007** [comment]
This button already exists. 👀
Please add another animated button.

**Comment by rcode321** [comment]
noted i'll create a new one

**Comment by rcode321** [comment]
can i use same branch?

**Comment by Spyware007** [comment]
Yes Ofcourse. 🚀

**Comment by Spyware007** [comment]
Thank you for your contribution. 🚀
Star the repo. 🌟

**Comment by rcode321** [comment]
yep done, thanks :) happy coding :)

**Pull request merged**
