### PR TITLE
Removed text decoration from navbar items

### LINKED ISSUE #1571: [Add] Remove the text decoration from Navbar links
### Details

Hey @Spyware007 I want to remove the text decoration present in the links of the navbar. Currently due to this the UI is not looking good. Pease assign me this issue. Thank you!

### Screenshots

image

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Fixes Issue

Closes #1571 

## Changes proposed

Hey @Spyware007 I have removed the text-decoration from navbar items. Please review my pr and merge it. Thanks!

## Screenshots

- Before:-

image

- After:-

image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
#1557 
This issue is already taken!

**Comment by sumitkr2000** [comment]
@Spyware007 Bhai fir assign kyu krte ho issue??

**Comment by Spyware007** [comment]
@sumitkr2000 Ohh Sorry my bad!

**Comment by sumitkr2000** [comment]
> @sumitkr2000 Ohh Sorry my bad!

Bro issue assign ho gya that tabhi pr kiya

**Pull request merged**
