### PR TITLE
Added Button and Corrected the javascript fetch path

### PR DESCRIPTION
**Pull request by ayushkumarbhadani**
## Fixes Issue: #1025 

Closes #issue_number: #1025

## Changes proposed
Added a New Button

## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/73775939/2fb0618d-624e-455b-85a3-485a04617de7

## Checklist

- [X] You've linked this PR to the correct issue.
- [X] You have checked that the code is working correctly.
- [X] You ⭐️ the repository!

## Note to reviewers

### CODE REVIEW

**Comment by ayushkumarbhadani** [comment]
Hey @Spyware007, Kindly review the PR and Merge it.
Thanks 😊

**Comment by PoorviShetty** [comment]
Please change only the necessary files, especially in src folder

**Comment by ayushkumarbhadani** [comment]
I have changed only the necessary files @PoorviShetty

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by ayushkumarbhadani** [comment]
> # Please check #1346

Okay, but today is the 19th of June, and time is still remaining, can you merge my PR for now?

**Comment by Spyware007** [comment]
Hello @ayushkumarbhadani 
It has some errors, I tried to fix it!
Closing this!

**Pull request closed without merging**
