### PR TITLE
siva button

### PR DESCRIPTION
**Pull request by Sathasivamthirumoorthi**

### CODE REVIEW

**Comment by Spyware007** [comment]
@Sathasivamthirumoorthi Change index.css to style.css
and add your folder name in [Data.js](https://github.com/Spyware007/Animating-Buttons/blob/main/src/Data.js)

**Comment by Sathasivamthirumoorthi** [comment]
@Spyware007  i have changed the filename to style.css and also added name in Data.js

**Comment by Sathasivamthirumoorthi** [comment]
can you please review and merge

**Comment by Spyware007** [comment]
@Sathasivamthirumoorthi Link style.css in an index.html file

**Comment by Sathasivamthirumoorthi** [comment]
really sorry @Spyware007  , now i am linked the css

**Comment by Sathasivamthirumoorthi** [comment]
can you please accept and merge

**Comment by Spyware007** [comment]
See this [here](https://lets-animate-buttons-git-fork-sathasivamthiru-c4255c-spyware007.vercel.app/)

Screenshot 2022-10-25 at 4 09 40 PM

Also, Fix the merge conflicts.

**Comment by Sathasivamthirumoorthi** [comment]
@Spyware007 Sorry for that issue , now everything corrected and fixed

**Comment by Arjun-Ingole** [comment]
Yes the issues are seems to be fixed now, Please pull the main branch into your fork and then make your changes as it has conflicts with the base. Please Open a new PR after doing these changes, Your contribution will be accepted next time

**Pull request closed without merging**
