### PR TITLE
Added a Slicer Button

### PR DESCRIPTION
**Pull request by ganraj21**
I have added a new Slicer Button
Screenshot (27)

### CODE REVIEW

**Comment by Spyware007** [comment]
@ganraj21  Please make a separate pull request for each button.
You did an amazing work but to make commit history cleaner make separate PRs.

**Comment by ganraj21** [comment]
@Spyware007 Can i delete this fork . I will make a fork again and then make separate PRs .   But can you tell me If i delete this then my previous merge will deleted or Not .

**Comment by Spyware007** [comment]
@ganraj21 Merged ones will not get affected.

**Comment by ganraj21** [comment]
Thank you @Spyware007

**Pull request merged**
