### PR TITLE
Added Slanty Wavy Button

### LINKED ISSUE #1351: [Add] Slanted wavy button
### Details

https://github.com/Spyware007/Animating-Buttons/assets/119161467/594621fb-ebe3-4549-a4b7-8ceecaf10d2b

### Screenshots

image

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

@TANYA-CHAN Please assign this issue

### PR DESCRIPTION
**Pull request by lakhan06**
## Fixes Issue

Closes #1351 

## Changes proposed
I added a slanty wavy Button 

## Screenshots
image

https://github.com/Spyware007/Animating-Buttons/assets/119161467/cd03a6ca-aa1c-4dbd-bd35-05ac1f424b81

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers
@Souravvmishra  I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

### CODE REVIEW

**Comment by Souravvmishra** [comment]
Looks Great. But it's overflowing. Align it at the centre

**Comment by lakhan06** [comment]
> Looks Great. But it's overflowing. Align it at the centre

okay

**Comment by lakhan06** [comment]
@Souravvmishra  I Have done some changes can you please check it now

**Comment by Souravvmishra** [comment]
Great But it seems you removed one of the two ways. Anyways I merged it.

**Comment by lakhan06** [comment]
> Great But it seems you removed one of the two ways. Anyways I merged it.
 @Souravvmishra  thankyou for merging my pull request but can you please add some level to my pull reuest so that i can get some points from my contribution and can you also add gssoc tag to it please.
Thankyou

**Comment by lakhan06** [comment]
Thank You @Souravvmishra  Sir for considering my request

**Pull request merged**
