### PR TITLE
Made button using Javascript

### PR DESCRIPTION
**Pull request by Siddharth961**
a wave button made using html, css and basic javascript.

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please modify Data.js, refer Readme

**Comment by Siddharth961** [comment]
@PoorviShetty sorry, i didn't go through readme in the first place, do i just add the folder name in Data.js ? It says to add the code too but all i see are the folder names in Data.js.

**Comment by PoorviShetty** [comment]
Just make a new commit with the changes, you don't need to make a fresh PR

**Comment by Siddharth961** [comment]
@PoorviShetty thanks just made a commit to add name in Data.js. Please check it out now

**Pull request merged**
