### PR TITLE
Created a button using HTML and CSS

### PR DESCRIPTION
**Pull request by Chandak-Keshav**
Added a swipe right sort of button using html and css.
Kindly accept my pr.
Thanks

### CODE REVIEW

**Comment by Spyware007** [comment]
You forgot to add your folder name in the [Data.js](https://github.com/Spyware007/Animating-Buttons/blob/main/src/Data.js) file

**Comment by Chandak-Keshav** [comment]
Added folder name in Data.js file @Spyware007

**Comment by Spyware007** [comment]
This animation is already present.
Please try adding another animated button.

**Comment by Chandak-Keshav** [comment]
Made changes @Spyware007 .
Hope this contribution helps.
If any changes are needed, I will be glad to do them.
Thank you

**Comment by Spyware007** [comment]
Thank you for your contribution. 🤩
Leave a star if you like. 🌟

**Pull request merged**
