### PR TITLE
Adding new button

### PR DESCRIPTION
**Pull request by lmalkam**
#305

### CODE REVIEW

**Comment by Spyware007** [comment]
@lmalkam  Hello

You forgot the Data.js part (Refer Readme.md for this.)
It will get merged once you complete adding your folder name in the Data.js file.

**Comment by Spyware007** [comment]
@lmalkam Are you still working on this?

**Comment by lmalkam** [comment]
@Spyware007 yes i am working on it

**Comment by Spyware007** [comment]
@lmalkam Please remove package-lock.json from your commits.

**Comment by lmalkam** [comment]
@Spyware007 i removed package-llock.json

**Comment by Spyware007** [comment]
@lmalkam 

Looking forward to more contributions from you. 🧑‍💻 
Thank you so much for your contribution.🌟

Make sure to ⭐ and follow me.
 I would love to connect with you all ❤️
 https://www.linkedin.com/in/om-gawande/

**Pull request merged**
