### PR TITLE
footer with dark_mode and white icons

### PR DESCRIPTION
**Pull request by rbeaujon**

### CODE REVIEW

**Comment by Spyware007** [comment]
@rbeaujon Can you please also make the footer responsive? ✨

**Comment by rbeaujon** [comment]
yes I already saw it sorry... let me finish this one and if nobody has
taken it , I will do it

**Comment by Spyware007** [comment]
@rbeaujon I will assign it to you! And merge this!
Thank you for your contribution ✨
Leave a 🌟 if you like.

**Comment by rbeaujon** [comment]
I already pushed the changes  for the buttons on Dark Mode. Tomorrow I
check the other ticket but I didn't see assigned to me yet.

Have a good night

**Pull request merged**
