### PR TITLE
#492 Solved

### PR DESCRIPTION
**Pull request by PayalPadmalyaPrusty**

### CODE REVIEW

**Comment by PoorviShetty** [comment]
@PayalPadmalyaPrusty Please go through the Readme for file naming conventions, uncommit the unnecessary files and modify Data.js

**Comment by PayalPadmalyaPrusty** [comment]
> @PayalPadmalyaPrusty Please go through the Readme for file naming conventions, uncommit the unnecessary files and modify Data.js

I have put the file name as my github username according to the Readme.md and i have not commited any data.js file .Kindly check my commits

**Comment by PoorviShetty** [comment]
> > @PayalPadmalyaPrusty Please go through the Readme for file naming conventions, uncommit the unnecessary files and modify Data.js
> 
> I have put the file name as my github username according to the Readme.md and i have not commited any data.js file .Kindly check my commits

You have to modify Data.js, please look at Readme again

**Comment by PayalPadmalyaPrusty** [comment]
@PoorviShetty I have updated the data.js file .Can you please check it

**Pull request merged**
