### PR TITLE
Added Snapchat button animation 

### PR DESCRIPTION
**Pull request by ankit071105**
## Screenshots

# Before :->

Screenshot 2023-07-23 at 10 43 57 PM

# On hover  :->

Screenshot 2023-07-23 at 10 44 07 PM

### CODE REVIEW

**Comment by ankit071105** [comment]
@Souravvmishra WHY  YOU HAVE CLOSE THE PULL REQUEST IT'S AN ANIMATION BUTTON

**Comment by Souravvmishra** [comment]
We're no longer accepting PRs for new button adding.

**Comment by Souravvmishra** [comment]
Apologies for the inconveniences caused

**Comment by ankit071105** [comment]
OK

**Pull request closed without merging**
