### PR TITLE
Added 2 new buttons and fixed previous two buttons one by adjusting the size and one by adding a new button 

### LINKED ISSUE #730: Fixing buttons
**This is a(n):**

- [x] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Screenshot 2023-05-29 000321

Screenshot 2023-05-29 000312

These 2 buttons have errors

- 1st button's text is not visible due to larger size
- 2nd is not a button there may be some error in the code
- I want to add a button in place of 2nd button which I have provided through the screen-shot

Please assign me in these issues @Spyware007

### LINKED ISSUE #733: Adding new 2 buttons
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to add 2 new animated buttons

- Hover Effect Button
- Read More button

### PR DESCRIPTION
**Pull request by Soumyajit2825**
Created 2 buttons and fix the errors that I have mentioned @Spyware007 
This closed #733 
This closed #730 
(doing a single PR for both issue)

Screenshots:- 

Screenshot 2023-05-29 025953
<br>
Screenshot 2023-05-29 030013

Thank You

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@Spyware007 Have you checked my changes ?

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it

**Comment by Soumyajit2825** [comment]
@PoorviShetty Ok
The error was from my side
Fixed
Now please check 
Thank You @Spyware007

**Comment by Soumyajit2825** [comment]
@Spyware007 @PoorviShetty Everyone is adding their data in the Data.js file and it's showing merge conflicts
Can you please merge it 
Otherwise I have to merge conflicts everyday!!

**Pull request merged**
