### PR TITLE
Animated  button

### LINKED ISSUE #1200: NEW BUTTON
### Details

I want to add a new button with a beautiful hover effect
Screenshot 2023-06-11 082957

### Screenshots

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Rahul-web-hub**
## created a new button having a beautiful design

Closes #1200 

## Changes proposed
 I have added a new button with hover effect and yellow orange colour combination

## Screenshots
Screenshot 2023-06-11 082957

## Checklist

- [ X] You've linked this PR to the correct issue.
- [X ] You have checked that the code is working correctly.
- [X ] You ⭐️ the repository!

### CODE REVIEW

**Comment by Souravvmishra** [comment]
You Forget To Add Name To Data.js

**Comment by Rahul-web-hub** [comment]
> You Forget To Add Name To Data.js
oh ok sir i will add it .Thanks for your suggestion

**Comment by TANYA-CHAN** [comment]
ReadMe instructions to be followed and reupload again, Data.js file is also missing

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Closing this as invalid
You had created a repository inside public/

**Pull request closed without merging**
