### PR TITLE
docs: format and make necessary changes

### LINKED ISSUE #925: docs: correct readme with proper format
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

image

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #925

## Screenshots

image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

<hr>

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Spyware007
Could you please review this pull request :)

**Comment by TANYA-CHAN** [comment]
Document changes will be merged only after tmrw evening

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
@Anmol-Baranwal We are changing the Readme.md and the workflow of the project!
So closing this as not required!

**Pull request closed without merging**
