### PR TITLE
Added a new click animation "About Us" button

### LINKED ISSUE #789: Add a new click animation "About Us" button [GSSOC'23]
This is a(n):

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

Details:
I want to add a new click animation button. That looks like this
https://github.com/Spyware007/Animating-Buttons/assets/120516365/a48fdc4a-5cd0-4c7d-982d-90f19257613d

please assign me this issue.

### PR DESCRIPTION
**Pull request by yaswika0311**
## Fixes Issue

Closes #789

## Changes Proposed
Added a new click animation button after referring to a youtube video

## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/120516365/f76bf02f-dbb8-4e53-87aa-82bd1f04ac8e

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note
Please kindly review, add labels and merge

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please resolve the merge conflicts

**Comment by TANYA-CHAN** [comment]
Please mention your name in the Data.js file and reupload

**Comment by yaswika0311** [comment]
Is it okay now?

**Comment by yaswika0311** [comment]
Is it okay now??

**Review by TANYA-CHAN — APPROVED** [review]

**Pull request merged**
