### PR TITLE
 new animation button added

### PR DESCRIPTION
**Pull request by HimanshuNarware**
Closes #issue_number
#1104
## Changes proposed
Added a new animation button on the website.

## Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/83147410/ce5379a0-ec26-464b-8ed3-f815a566aff1

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Souravvmishra** [comment]
Please check the deployment once @HimanshuNarware

**Comment by HimanshuNarware** [comment]
> Please check the deployment once @HimanshuNarware

All conflict clear

**Comment by Souravvmishra** [comment]
Update the data.js to add your name at the last or at the very beginning

**Comment by HimanshuNarware** [comment]
> Update the data.js to add your name at the last or at the very beginning

ok

**Pull request merged**
