### PR TITLE
new button added

### PR DESCRIPTION
**Pull request by shruuti321**
## Fixes Issue

Closes #1184

## Screenshots

image

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by shruuti321** [comment]
Kindly review my pr

**Comment by Souravvmishra** [comment]
Fix the conflicts

**Comment by TANYA-CHAN** [comment]
Please remove all the extra files and only have:- index, app, style and data following the Readme

**Comment by Spyware007** [comment]
# Please check #1346

**Pull request merged**
