### PR TITLE
Remove duplicate buttons

### PR DESCRIPTION
**Pull request by LucianeFernandesRoque**
**Objective**
Remove duplicate animation buttons.

[Remove duplicate animation buttons. sweat_smile](https://github.com/Spyware007/Animating-Buttons/issues/99)

### CODE REVIEW

**Comment by Spyware007** [comment]
Can you please share the Images of duplicate buttons.

**Comment by LucianeFernandesRoque** [comment]
> Can you please share the Images of duplicate buttons.

Sure, I think these two buttons are almost the same
Screenshot from 2022-10-19 19-41-31
Screenshot from 2022-10-19 19-41-16
Screenshot from 2022-10-19 19-37-15
Screenshot from 2022-10-19 19-36-50

**Comment by Spyware007** [comment]
Hey, @LucianeFernandesRoque in terms of animation they are different. 👀

**Comment by LucianeFernandesRoque** [comment]
> Hey, @LucianeFernandesRoque in terms of animation they are different. 👀
> 
sorry, I thought these two buttons were the same, but from what I saw here they are different

**Comment by Spyware007** [comment]
Nevermind @LucianeFernandesRoque . 
I'm closing this PR for now.
If you find any duplicate buttons or want to add a new animated button you are welcome.

**Comment by LucianeFernandesRoque** [comment]
> Nevermind @LucianeFernandesRoque . 
> I'm closing this PR for now.
> If you find any duplicate buttons or want to add a new animated button you are welcome.

Thanks for all.

**Pull request closed without merging**
