### PR TITLE
Added sea mode toggle button

### LINKED ISSUE #1262: [Add] <Add sea mode button>
### Details

 Sea mode button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/120560129/72885586-0bd0-4d9a-9610-5e5f3283555f

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by madhurafulkar**
## Fixes Issue

Closes #1262 

## Changes proposed

Added sea mode toggle button

## Screenshots
Screenshot 2023-06-16 111929

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Comment by Spyware007** [comment]
@madhurafulkar  Hello, that's a very cool button!
Can you please resolve the merge conflicts of Data.js and please remove the package-lock.json file from the commit.
Thank you so much!

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
resolve conflicts ASAP.

**Comment by madhurafulkar** [comment]
I had resolved the conflicts in pull request No. #1371

**Review by TANYA-CHAN — CHANGES_REQUESTED** [review]
more time needed to resolve conflicts

**Pull request closed without merging**
