### PR TITLE
Show the number of forks, stars and contributors on the home page

### PR DESCRIPTION
**Pull request by amratansh12**
Added the github forks, stars and contributors number info below the navigation bar

### CODE REVIEW

**Comment by Spyware007** [comment]
@amratansh12 It looks good enough for now.

Can you fix the merge conflicts?
I will merge it then!

**Comment by amratansh12** [comment]
@Spyware007 Done. Conflicts resolved.

**Comment by PoorviShetty** [comment]
@amratansh12 There seems to be a merge conflict, please resolve it.

**Comment by amratansh12** [comment]
@PoorviShetty Conflicts resolved. PR ready to be merged.

**Pull request closed without merging**
