### PR TITLE
Added Navigation feature to show codes for the buttons instead of downloading it #290

### PR DESCRIPTION
**Pull request by adity2911**
New Web Page Designed Showing Files of code on the Web Page directory #290

Checklist:
- [x] : Routing Implementation to the new Web Page where the code can be copied from.
- [x] : adding Show Code button below every button on the main page.
- [x] : Designing the WebPage.
- [x] : Import files of the indivisual button
- [x] : Displaying indivisual code sections of HTML, CSS and JS.

image

### CODE REVIEW

**Comment by adity2911** [comment]
can you give me permission to resolve conflicts?

**Comment by adity2911** [comment]
The conflicts here are actually actually because I installed a package react-router-dom.

**Comment by adity2911** [comment]
Conflict Resolved

**Comment by adity2911** [comment]
Future Goals:
- Redesign of the UI
- Betterment of Dark Mode
- Make the code such that changing it propagates to the displayed button

**Comment by adity2911** [comment]
@Spyware007 
Conflicts have been resolved.
Thank you so much for your appreciation and acknowledgement.
Happy to be working on the project.

**Comment by Spyware007** [comment]
Thank you so much @adity2911 !
You can further work on this 

Future Goals:

Redesign of the UI
Betterment of Dark Mode
Make the code such that changing it propagates to the displayed button

I will assign it to you just create a PR.

Tip: Make separate PRs for each one to get more points and top the leaderboard.

Once again Thank you so much.

**Comment by adity2911** [comment]
Actually before we do that, There is some error due to resolve conflict.
The showPage button is missing from the main page.
If you allow me just some time to reslove the error right now, I think It will be better for the codebase.

**Comment by Spyware007** [comment]
@adity2911  yeah sure!
I texted you on discord for the same!

**Comment by adity2911** [comment]
I have fixed it
can you merge the PR?

**Pull request merged**
