### PR TITLE
add new sparkling button

### PR DESCRIPTION
**Pull request by Vedu1004**
## Fixes Issue

Closes #issue_number

## Checklist

- [ ] You've linked this PR to the correct issue.
- [ ] You have checked that the code is working correctly.
- [ ] You ⭐️ the repository!

### CODE REVIEW

**Review by Souravvmishra — COMMENTED** [review]
Add Name To Data.Js & is the button made in react?

**Comment by Vedu1004** [comment]
No the button is in javascript

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Closing this as invalid!

**Pull request closed without merging**
