### PR TITLE
Added button using Javascript

### PR DESCRIPTION
**Pull request by sagnik3788**
issue #304 solved

### CODE REVIEW

**Comment by Spyware007** [comment]
Hello @sagnik3788 
You forgot the Data.js part (Refer Readme.md for this.)

It will get merged once you complete adding your folder name in the Data.js file.

**Comment by sagnik3788** [comment]
ok @Spyware007

**Comment by sagnik3788** [comment]
can i update this pr or i want to create a new pr

**Comment by Spyware007** [comment]
@sagnik3788 You can update this PR by pushing code to your froked repo!

**Comment by Spyware007** [comment]
@sagnik3788 Are you still working on this?

**Comment by sagnik3788** [comment]
No, i update the  Data.js part @Spyware007

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Pull request merged**
