### PR TITLE
Successfully New button added

### PR DESCRIPTION
**Pull request by ani0722**
Screenshot 2023-05-24 at 8 54 47 PM

The command button has been added successfully and is working.

### CODE REVIEW

**Comment by ani0722** [comment]
@Spyware007 pls add this button

**Comment by ani0722** [comment]
@Spyware007 
I Have updated and there are no conflicts please review it and accept it. Thank you!

**Comment by PoorviShetty** [comment]
Hi, there seems to be a merge conflict, please resolve it.

**Comment by ani0722** [comment]
The conflict has been resolved. Thank you. Please review and accept it. @PoorviShetty

**Pull request merged**
