### PR TITLE
Added Button hover effect using transform issues-#1056

### LINKED ISSUE #1056: Button hover effect using transform
## Description

As part of our ongoing development, we aim to implement a button hover effect using the CSS `transform` property. This will enhance the visual appeal and interactivity of our buttons, providing a smooth transition and engaging user experience.

### Problem Statement

Currently, our buttons lack dynamic visual feedback when users interact with them. The absence of hover effects can make the buttons feel static and less engaging. This may impact the overall user experience and diminish the visual appeal of our interface.

### Proposed Solution

The goal of this issue is to introduce a button hover effect using the `transform` property to create an interactive and visually appealing experience. When users hover over a button, it should smoothly transition in response to the hover action, such as scaling, rotating, or changing color. This effect will provide immediate visual feedback and enhance the perceived interactivity of our buttons.

Adding a hover effect to  buttons will significantly enhance the user experience by providing a visually appealing and interactive interface.

### Screenshots

Screenshot (799)
Screenshot (800)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishusk**
## Fixes Issue

Closes #1056

## Changes proposed
The button hover effect feature adds dynamic visual feedback to buttons on our website. When users hover over a button, it smoothly transitions using CSS transforms, providing an engaging and interactive user experience. 

## Screenshots

Screenshot (799)
Screenshot (800)

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

## Note to reviewers

We welcome contributions to improve the button hover effect feature. If you have any suggestions, bug fixes, or enhancements, please submit a pull request following the project's contribution guidelines.

### CODE REVIEW

**Comment by PoorviShetty** [comment]
Please resolve the merge conflicts, remove the unnecessary folder in src

**Comment by TANYA-CHAN** [comment]
Please upload all the button files one by one only, remove all the extra files and only follow the ones written in the ReadMe

**Comment by Nishusk** [comment]
> Please upload all the button files one by one only, remove all the extra files and only reupload the ones written in the ReadMe

 I will proceed with this task and ensure that only the necessary files are uploaded.

**Comment by Spyware007** [comment]
# Please check #1346

**Pull request merged**
