### PR TITLE
Added a new button

### PR DESCRIPTION
**Pull request by uddinArsalan**
I have attached a new fancy button with having click and hover effect
please accept my PR

### CODE REVIEW

**Comment by Arjun-Ingole** [comment]
Please get rid of the text that is outside the button and only keep the button in center, Fix these issues and Tag me once done, Rest seems fine

**Comment by uddinArsalan** [comment]
Hey @Arjun-Ingole , I have made the required changes you can consider submitting the pull request now

**Comment by Arjun-Ingole** [comment]
The Button isn't centered correctly and also you've included .vscode config in your PR which is irrelevant, Please fix these issues to get your PR merged

**Comment by uddinArsalan** [comment]
Hey @Arjun-Ingole I have run into some problems in the code base can I close this pull request and make a new one with the desired changes

**Comment by Arjun-Ingole** [comment]
> Hey @Arjun-Ingole I have run into some problems in the code base can I close this pull request and make a new one with the desired changes

Yes

**Pull request closed without merging**
