### PR TITLE
Wavy Animation Button Added

### PR DESCRIPTION
**Pull request by kishanlalchoudhary**
Hi @Spyware007
Myself Kishanlal Choudhary,
I want to add a wavy animation button  ,kindly merge  my pull request under hactoberfest if its ok
#hactoberfest2022.
Thank You.

### CODE REVIEW

**Comment by kishanlalchoudhary** [comment]
let me know after merging my pr

**Comment by kishanlalchoudhary** [comment]
or if any changes are required

**Comment by Spyware007** [comment]
You need to host the image somewhere to use it as while downloading the image will not get downloaded. 👀
Resolve the conflicts.

**Comment by kishanlalchoudhary** [comment]
How to host image

**Comment by kishanlalchoudhary** [comment]
i have resolved conflicts

**Comment by kishanlalchoudhary** [comment]
without image also there is other animation

**Comment by kishanlalchoudhary** [comment]
so you can upload by deleting image

**Pull request merged**
