### PR TITLE
Circular Hover Button

### LINKED ISSUE #1527: Circular Hover Button
### Details

Technologies Used:
HTML
CSS

ScreenShort:
image

### Screenshots

Demo Vedio:

https://github.com/Spyware007/Animating-Buttons/assets/98798977/eec64d96-8ba4-4aa3-8195-0e816c2e6384

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Durgesh4993**
## Fixes Issue

Closes #1527

## Screenshots
image

Demo Vedio:

https://github.com/Spyware007/Animating-Buttons/assets/98798977/eec64d96-8ba4-4aa3-8195-0e816c2e6384

## Checklist

- [x] You've linked this PR to the correct issue.
- [x] You have checked that the code is working correctly.
- [x] You ⭐️ the repository!

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Spyware007 Please review and merge it

**Comment by Durgesh4993** [comment]
@adity2911 Please review and merge it

**Comment by adity2911** [comment]
It is not possible to merge new animation buttons

**Comment by Durgesh4993** [comment]
@adity2911 So can i create new button or update anything

**Pull request closed without merging**
